/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed successes of method [`create_custom_tracking_domain`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CreateCustomTrackingDomainSuccess {
    Status201(models::CustomTrackingDomain),
    Status202(models::DnsSetupRequired),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CreateCustomTrackingDomainSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CreateCustomTrackingDomainSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`delete_custom_tracking_domain`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum DeleteCustomTrackingDomainSuccess {
    Status204(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for DeleteCustomTrackingDomainSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DeleteCustomTrackingDomainSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`list_custom_tracking_domains`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListCustomTrackingDomainsSuccess {
    Status200(models::CustomTrackingDomainListResponse),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListCustomTrackingDomainsSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListCustomTrackingDomainsSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`update_custom_tracking_domain`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum UpdateCustomTrackingDomainSuccess {
    Status200(models::CustomTrackingDomain),
    Status202(models::DnsSetupRequired),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for UpdateCustomTrackingDomainSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("UpdateCustomTrackingDomainSuccess { [REDACTED] }")
    }
}

/// struct for typed errors of method [`create_custom_tracking_domain`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CreateCustomTrackingDomainError {
    Status400(models::ErrorResponse),
    Status403(),
    Status409(),
    Status422(models::DnsSetupRequired),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CreateCustomTrackingDomainError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CreateCustomTrackingDomainError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`delete_custom_tracking_domain`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum DeleteCustomTrackingDomainError {
    Status400(models::ErrorResponse),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for DeleteCustomTrackingDomainError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DeleteCustomTrackingDomainError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`list_custom_tracking_domains`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListCustomTrackingDomainsError {
    Status400(models::ErrorResponse),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListCustomTrackingDomainsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListCustomTrackingDomainsError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`update_custom_tracking_domain`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum UpdateCustomTrackingDomainError {
    Status400(models::ErrorResponse),
    Status403(),
    Status404(),
    Status409(),
    Status422(models::DnsSetupRequired),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for UpdateCustomTrackingDomainError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("UpdateCustomTrackingDomainError { [REDACTED] }")
    }
}

/// Register a custom branded domain for click tracking, open tracking, or unsubscribe handling. By default, MailChannels uses shared domains for these links. Using a custom domain improves brand consistency by replacing shared domains with your own (e.g., click.example.com). Once registered, select the domain at send time using its `name`.  Before registration completes, two DNS records must be in place: 1. A TXT record at `_mailchannels-verify.<hostname>` containing the verification token    (returned in the 202 response). 2. A CNAME record at `<hostname>` pointing to `links.mailchannels.net`.
pub async fn create_custom_tracking_domain(
    configuration: &configuration::Configuration,
    x_api_key: &str,
    post_custom_tracking_domain_request: models::PostCustomTrackingDomainRequest,
) -> Result<
    ResponseContent<CreateCustomTrackingDomainSuccess>,
    Error<CreateCustomTrackingDomainError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;
    let p_body_post_custom_tracking_domain_request = post_custom_tracking_domain_request;

    let uri_str = format!("{}/custom-tracking-domains", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());
    req_builder = req_builder.json(&p_body_post_custom_tracking_domain_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            201 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(CreateCustomTrackingDomainSuccess::Status201(
                        serde_json::from_str(&content)?,
                    ))
                }
            }

            202 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(CreateCustomTrackingDomainSuccess::Status202(
                        serde_json::from_str(&content)?,
                    ))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(CreateCustomTrackingDomainSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(CreateCustomTrackingDomainError::Status400),

            403 => Some(CreateCustomTrackingDomainError::Status403()),

            409 => Some(CreateCustomTrackingDomainError::Status409()),

            422 => serde_json::from_str(&content)
                .ok()
                .map(CreateCustomTrackingDomainError::Status422),

            500 => Some(CreateCustomTrackingDomainError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(CreateCustomTrackingDomainError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Permanently delete an existing custom tracking domain for the given hostname and scope. The domain can be re-registered if needed. WARNING: Any tracking links or unsubscribe URLs in previously sent emails using this domain will stop working immediately.
pub async fn delete_custom_tracking_domain(
    configuration: &configuration::Configuration,
    hostname: &str,
    scope: &str,
    x_api_key: &str,
) -> Result<
    ResponseContent<DeleteCustomTrackingDomainSuccess>,
    Error<DeleteCustomTrackingDomainError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_hostname = hostname;
    let p_path_scope = scope;
    let p_header_x_api_key = x_api_key;

    let uri_str = format!(
        "{}/custom-tracking-domains/{hostname}/{scope}",
        configuration.base_path,
        hostname = crate::apis::urlencode(p_path_hostname),
        scope = crate::apis::urlencode(p_path_scope)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            204 => Some(DeleteCustomTrackingDomainSuccess::Status204()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(DeleteCustomTrackingDomainSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(DeleteCustomTrackingDomainError::Status400),

            500 => Some(DeleteCustomTrackingDomainError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(DeleteCustomTrackingDomainError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve all custom tracking domains registered under your account. Optional filters include domain name, status, scope, limit and offset.
pub async fn list_custom_tracking_domains(
    configuration: &configuration::Configuration,
    x_api_key: &str,
    name: Option<&str>,
    status: Option<&str>,
    scope: Option<&str>,
    limit: Option<i32>,
    offset: Option<i32>,
) -> Result<ResponseContent<ListCustomTrackingDomainsSuccess>, Error<ListCustomTrackingDomainsError>>
{
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;
    let p_query_name = name;
    let p_query_status = status;
    let p_query_scope = scope;
    let p_query_limit = limit;
    let p_query_offset = offset;

    let uri_str = format!("{}/custom-tracking-domains", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_name {
        req_builder = req_builder.query(&[("name", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_status {
        req_builder = req_builder.query(&[("status", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_scope {
        req_builder = req_builder.query(&[("scope", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(ListCustomTrackingDomainsSuccess::Status200(
                        serde_json::from_str(&content)?,
                    ))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListCustomTrackingDomainsSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(ListCustomTrackingDomainsError::Status400),

            500 => Some(ListCustomTrackingDomainsError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListCustomTrackingDomainsError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Update an existing custom tracking domain by its hostname and scope. Supports updating the custom tracking domain's name or toggling its active status.
pub async fn update_custom_tracking_domain(
    configuration: &configuration::Configuration,
    hostname: &str,
    scope: &str,
    x_api_key: &str,
    patch_custom_tracking_domain_request: models::PatchCustomTrackingDomainRequest,
) -> Result<
    ResponseContent<UpdateCustomTrackingDomainSuccess>,
    Error<UpdateCustomTrackingDomainError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_hostname = hostname;
    let p_path_scope = scope;
    let p_header_x_api_key = x_api_key;
    let p_body_patch_custom_tracking_domain_request = patch_custom_tracking_domain_request;

    let uri_str = format!(
        "{}/custom-tracking-domains/{hostname}/{scope}",
        configuration.base_path,
        hostname = crate::apis::urlencode(p_path_hostname),
        scope = crate::apis::urlencode(p_path_scope)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());
    req_builder = req_builder.json(&p_body_patch_custom_tracking_domain_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(UpdateCustomTrackingDomainSuccess::Status200(
                        serde_json::from_str(&content)?,
                    ))
                }
            }

            202 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(UpdateCustomTrackingDomainSuccess::Status202(
                        serde_json::from_str(&content)?,
                    ))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(UpdateCustomTrackingDomainSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(UpdateCustomTrackingDomainError::Status400),

            403 => Some(UpdateCustomTrackingDomainError::Status403()),

            404 => Some(UpdateCustomTrackingDomainError::Status404()),

            409 => Some(UpdateCustomTrackingDomainError::Status409()),

            422 => serde_json::from_str(&content)
                .ok()
                .map(UpdateCustomTrackingDomainError::Status422),

            500 => Some(UpdateCustomTrackingDomainError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(UpdateCustomTrackingDomainError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
