/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed successes of method [`check_domain`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CheckDomainSuccess {
    Status200(models::CheckDomainResult),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CheckDomainSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CheckDomainSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`create_dkim_key`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CreateDkimKeySuccess {
    Status201(models::DkimKeyInfo),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CreateDkimKeySuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CreateDkimKeySuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`list_dkim_keys`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListDkimKeysSuccess {
    Status200(models::DkimKeyList),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListDkimKeysSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListDkimKeysSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`rotate_dkim_key`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum RotateDkimKeySuccess {
    Status201(models::DkimKeyRotateResponse),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for RotateDkimKeySuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("RotateDkimKeySuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`update_dkim_key`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum UpdateDkimKeySuccess {
    Status204(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for UpdateDkimKeySuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("UpdateDkimKeySuccess { [REDACTED] }")
    }
}

/// struct for typed errors of method [`check_domain`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CheckDomainError {
    Status400(models::ErrorResponse),
    Status403(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CheckDomainError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CheckDomainError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`create_dkim_key`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CreateDkimKeyError {
    Status400(models::ErrorResponse),
    Status409(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CreateDkimKeyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CreateDkimKeyError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`list_dkim_keys`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListDkimKeysError {
    Status400(models::ErrorResponse),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListDkimKeysError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListDkimKeysError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`rotate_dkim_key`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum RotateDkimKeyError {
    Status400(models::ErrorResponse),
    Status404(),
    Status409(),
    Status500(),
    Status503(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for RotateDkimKeyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("RotateDkimKeyError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`update_dkim_key`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum UpdateDkimKeyError {
    Status400(models::ErrorResponse),
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for UpdateDkimKeyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("UpdateDkimKeyError { [REDACTED] }")
    }
}

/// Validates a domain's email authentication setup by retrieving its DKIM, SPF, and Domain Lockdown status. This endpoint checks whether the domain is properly configured for secure email delivery.
pub async fn check_domain(
    configuration: &configuration::Configuration,
    x_api_key: &str,
    check_domain_body: models::CheckDomainBody,
) -> Result<ResponseContent<CheckDomainSuccess>, Error<CheckDomainError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;
    let p_body_check_domain_body = check_domain_body;

    let uri_str = format!("{}/check-domain", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());
    req_builder = req_builder.json(&p_body_check_domain_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(CheckDomainSuccess::Status200(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(CheckDomainSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(CheckDomainError::Status400),

            403 => Some(CheckDomainError::Status403()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(CheckDomainError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Create a DKIM key pair for a specified domain and selector using the specified algorithm and key length, for the current customer.
pub async fn create_dkim_key(
    configuration: &configuration::Configuration,
    domain: &str,
    x_api_key: &str,
    dkim_key_pair_create_request: models::DkimKeyPairCreateRequest,
) -> Result<ResponseContent<CreateDkimKeySuccess>, Error<CreateDkimKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_domain = domain;
    let p_header_x_api_key = x_api_key;
    let p_body_dkim_key_pair_create_request = dkim_key_pair_create_request;

    let uri_str = format!(
        "{}/domains/{domain}/dkim-keys",
        configuration.base_path,
        domain = crate::apis::urlencode(p_path_domain)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());
    req_builder = req_builder.json(&p_body_dkim_key_pair_create_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            201 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(CreateDkimKeySuccess::Status201(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(CreateDkimKeySuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(CreateDkimKeyError::Status400),

            409 => Some(CreateDkimKeyError::Status409()),

            500 => Some(CreateDkimKeyError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(CreateDkimKeyError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Search for DKIM keys by domain, with optional filters. If selector is provided, at most one key will be returned.
pub async fn list_dkim_keys(
    configuration: &configuration::Configuration,
    domain: &str,
    x_api_key: &str,
    selector: Option<&str>,
    status: Option<&str>,
    offset: Option<i32>,
    limit: Option<i32>,
    include_dns_record: Option<bool>,
) -> Result<ResponseContent<ListDkimKeysSuccess>, Error<ListDkimKeysError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_domain = domain;
    let p_header_x_api_key = x_api_key;
    let p_query_selector = selector;
    let p_query_status = status;
    let p_query_offset = offset;
    let p_query_limit = limit;
    let p_query_include_dns_record = include_dns_record;

    let uri_str = format!(
        "{}/domains/{domain}/dkim-keys",
        configuration.base_path,
        domain = crate::apis::urlencode(p_path_domain)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_selector {
        req_builder = req_builder.query(&[("selector", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_status {
        req_builder = req_builder.query(&[("status", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_include_dns_record {
        req_builder = req_builder.query(&[("include_dns_record", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(ListDkimKeysSuccess::Status200(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListDkimKeysSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(ListDkimKeysError::Status400),

            500 => Some(ListDkimKeysError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListDkimKeysError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Rotate an active DKIM key pair. Mark the original key as 'rotated', and create a new key pair with the required new key selector, reusing the same algorithm and key length. The rotated key remains valid for signing for a 3-day grace period, and is automatically changed to 'retired' 2 weeks after rotation. Publish the new key to its DNS TXT record before rotated key expires for signing as emails sent with an unpublished key will fail DKIM validation by receiving providers. After the grace period, only the new key is valid for signing if published.
pub async fn rotate_dkim_key(
    configuration: &configuration::Configuration,
    domain: &str,
    selector: &str,
    x_api_key: &str,
    dkim_key_rotate_request: models::DkimKeyRotateRequest,
) -> Result<ResponseContent<RotateDkimKeySuccess>, Error<RotateDkimKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_domain = domain;
    let p_path_selector = selector;
    let p_header_x_api_key = x_api_key;
    let p_body_dkim_key_rotate_request = dkim_key_rotate_request;

    let uri_str = format!(
        "{}/domains/{domain}/dkim-keys/{selector}/rotate",
        configuration.base_path,
        domain = crate::apis::urlencode(p_path_domain),
        selector = crate::apis::urlencode(p_path_selector)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());
    req_builder = req_builder.json(&p_body_dkim_key_rotate_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            201 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(RotateDkimKeySuccess::Status201(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(RotateDkimKeySuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(RotateDkimKeyError::Status400),

            404 => Some(RotateDkimKeyError::Status404()),

            409 => Some(RotateDkimKeyError::Status409()),

            500 => Some(RotateDkimKeyError::Status500()),

            503 => Some(RotateDkimKeyError::Status503()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(RotateDkimKeyError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Update fields of an existing DKIM key pair for the specified domain and selector, for the current customer. Currently, only the status field can be updated. revoked: Indicates that the key is compromised and should not be used. retired: Indicates that the key has been rotated and is no longer in use. rotated: Indicates that the key is going through the rotation process. Only active key pairs can be updated to this status, and no new key pair is created. The rotated key can be used to sign emails for 3 days after the status update, and will automatically change to 'retired' 2 weeks after update. For a smooth key transition, it is recommended to create and publish a new key pair before signing is disabled for the rotated key.
pub async fn update_dkim_key(
    configuration: &configuration::Configuration,
    domain: &str,
    selector: &str,
    x_api_key: &str,
    dkim_key_pair_update_request: models::DkimKeyPairUpdateRequest,
) -> Result<ResponseContent<UpdateDkimKeySuccess>, Error<UpdateDkimKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_domain = domain;
    let p_path_selector = selector;
    let p_header_x_api_key = x_api_key;
    let p_body_dkim_key_pair_update_request = dkim_key_pair_update_request;

    let uri_str = format!(
        "{}/domains/{domain}/dkim-keys/{selector}",
        configuration.base_path,
        domain = crate::apis::urlencode(p_path_domain),
        selector = crate::apis::urlencode(p_path_selector)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::PATCH, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());
    req_builder = req_builder.json(&p_body_dkim_key_pair_update_request);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            204 => Some(UpdateDkimKeySuccess::Status204()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(UpdateDkimKeySuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(UpdateDkimKeyError::Status400),

            404 => Some(UpdateDkimKeyError::Status404()),

            500 => Some(UpdateDkimKeyError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(UpdateDkimKeyError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
