/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed successes of method [`get_engagement_metrics`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetEngagementMetricsSuccess {
    Status200(models::MetricsEngagement),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetEngagementMetricsSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetEngagementMetricsSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`get_performance_metrics`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetPerformanceMetricsSuccess {
    Status200(models::MetricsPerformance),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetPerformanceMetricsSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetPerformanceMetricsSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`get_recipient_behaviour_metrics`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetRecipientBehaviourMetricsSuccess {
    Status200(models::MetricsRecipientBehaviour),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetRecipientBehaviourMetricsSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetRecipientBehaviourMetricsSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`get_sender_metrics`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetSenderMetricsSuccess {
    Status200(models::MetricsSenderResponse),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetSenderMetricsSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetSenderMetricsSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`get_volume_metrics`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetVolumeMetricsSuccess {
    Status200(models::MetricsVolume),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetVolumeMetricsSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetVolumeMetricsSuccess { [REDACTED] }")
    }
}

/// struct for typed errors of method [`get_engagement_metrics`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetEngagementMetricsError {
    Status400(models::ErrorResponse),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetEngagementMetricsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetEngagementMetricsError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`get_performance_metrics`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetPerformanceMetricsError {
    Status400(models::ErrorResponse),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetPerformanceMetricsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetPerformanceMetricsError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`get_recipient_behaviour_metrics`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetRecipientBehaviourMetricsError {
    Status400(models::ErrorResponse),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetRecipientBehaviourMetricsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetRecipientBehaviourMetricsError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`get_sender_metrics`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetSenderMetricsError {
    Status400(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetSenderMetricsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetSenderMetricsError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`get_volume_metrics`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetVolumeMetricsError {
    Status400(models::ErrorResponse),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetVolumeMetricsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetVolumeMetricsError { [REDACTED] }")
    }
}

/// Retrieve engagement metrics for messages sent from your account, including counts of open and click events. Supports optional filters for time range, and campaign ID.
pub async fn get_engagement_metrics(
    configuration: &configuration::Configuration,
    x_api_key: &str,
    start_time: Option<&str>,
    end_time: Option<&str>,
    campaign_id: Option<&str>,
    interval: Option<&str>,
) -> Result<ResponseContent<GetEngagementMetricsSuccess>, Error<GetEngagementMetricsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;
    let p_query_start_time = start_time;
    let p_query_end_time = end_time;
    let p_query_campaign_id = campaign_id;
    let p_query_interval = interval;

    let uri_str = format!("{}/metrics/engagement", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_start_time {
        req_builder = req_builder.query(&[("start_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_end_time {
        req_builder = req_builder.query(&[("end_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_campaign_id {
        req_builder = req_builder.query(&[("campaign_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_interval {
        req_builder = req_builder.query(&[("interval", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(GetEngagementMetricsSuccess::Status200(
                        serde_json::from_str(&content)?,
                    ))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetEngagementMetricsSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(GetEngagementMetricsError::Status400),

            500 => Some(GetEngagementMetricsError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetEngagementMetricsError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve performance metrics for messages sent from your account, including counts of processed, delivered, hard-bounced, and complained events. Supports optional filters for time range, and campaign ID.
pub async fn get_performance_metrics(
    configuration: &configuration::Configuration,
    x_api_key: &str,
    start_time: Option<&str>,
    end_time: Option<&str>,
    campaign_id: Option<&str>,
    interval: Option<&str>,
) -> Result<ResponseContent<GetPerformanceMetricsSuccess>, Error<GetPerformanceMetricsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;
    let p_query_start_time = start_time;
    let p_query_end_time = end_time;
    let p_query_campaign_id = campaign_id;
    let p_query_interval = interval;

    let uri_str = format!("{}/metrics/performance", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_start_time {
        req_builder = req_builder.query(&[("start_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_end_time {
        req_builder = req_builder.query(&[("end_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_campaign_id {
        req_builder = req_builder.query(&[("campaign_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_interval {
        req_builder = req_builder.query(&[("interval", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(GetPerformanceMetricsSuccess::Status200(
                        serde_json::from_str(&content)?,
                    ))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetPerformanceMetricsSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(GetPerformanceMetricsError::Status400),

            500 => Some(GetPerformanceMetricsError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetPerformanceMetricsError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve recipient behaviour metrics for messages sent from your account, including counts of unsubscribed events. Supports optional filters for time range, and campaign ID.
pub async fn get_recipient_behaviour_metrics(
    configuration: &configuration::Configuration,
    x_api_key: &str,
    start_time: Option<&str>,
    end_time: Option<&str>,
    campaign_id: Option<&str>,
    interval: Option<&str>,
) -> Result<
    ResponseContent<GetRecipientBehaviourMetricsSuccess>,
    Error<GetRecipientBehaviourMetricsError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;
    let p_query_start_time = start_time;
    let p_query_end_time = end_time;
    let p_query_campaign_id = campaign_id;
    let p_query_interval = interval;

    let uri_str = format!("{}/metrics/recipient-behaviour", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_start_time {
        req_builder = req_builder.query(&[("start_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_end_time {
        req_builder = req_builder.query(&[("end_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_campaign_id {
        req_builder = req_builder.query(&[("campaign_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_interval {
        req_builder = req_builder.query(&[("interval", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(GetRecipientBehaviourMetricsSuccess::Status200(
                        serde_json::from_str(&content)?,
                    ))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetRecipientBehaviourMetricsSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(GetRecipientBehaviourMetricsError::Status400),

            500 => Some(GetRecipientBehaviourMetricsError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetRecipientBehaviourMetricsError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves a list of senders, either sub-accounts or campaigns, with their associated message metrics. Sorted by total # of sent messages (processed + dropped) Supports optional filter for time range, and optional settings for limit, offset, and sort order. Note: senders without any messages in the given time range will not be included in the results. The default time range is from one month ago to now, and the default sort order is descending.
pub async fn get_sender_metrics(
    configuration: &configuration::Configuration,
    sender_type: &str,
    x_api_key: &str,
    start_time: Option<&str>,
    end_time: Option<&str>,
    limit: Option<i32>,
    offset: Option<i32>,
    sort_order: Option<&str>,
) -> Result<ResponseContent<GetSenderMetricsSuccess>, Error<GetSenderMetricsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_sender_type = sender_type;
    let p_header_x_api_key = x_api_key;
    let p_query_start_time = start_time;
    let p_query_end_time = end_time;
    let p_query_limit = limit;
    let p_query_offset = offset;
    let p_query_sort_order = sort_order;

    let uri_str = format!(
        "{}/metrics/senders/{sender_type}",
        configuration.base_path,
        sender_type = crate::apis::urlencode(p_path_sender_type)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_start_time {
        req_builder = req_builder.query(&[("start_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_end_time {
        req_builder = req_builder.query(&[("end_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_sort_order {
        req_builder = req_builder.query(&[("sort_order", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(GetSenderMetricsSuccess::Status200(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetSenderMetricsSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => Some(GetSenderMetricsError::Status400()),

            500 => Some(GetSenderMetricsError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetSenderMetricsError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve volume metrics for messages sent from your account, including counts of processed, delivered and dropped events. Supports optional filters for time range and campaign ID.
pub async fn get_volume_metrics(
    configuration: &configuration::Configuration,
    x_api_key: &str,
    start_time: Option<&str>,
    end_time: Option<&str>,
    campaign_id: Option<&str>,
    interval: Option<&str>,
) -> Result<ResponseContent<GetVolumeMetricsSuccess>, Error<GetVolumeMetricsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;
    let p_query_start_time = start_time;
    let p_query_end_time = end_time;
    let p_query_campaign_id = campaign_id;
    let p_query_interval = interval;

    let uri_str = format!("{}/metrics/volume", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_start_time {
        req_builder = req_builder.query(&[("start_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_end_time {
        req_builder = req_builder.query(&[("end_time", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_campaign_id {
        req_builder = req_builder.query(&[("campaign_id", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_interval {
        req_builder = req_builder.query(&[("interval", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(GetVolumeMetricsSuccess::Status200(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetVolumeMetricsSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(GetVolumeMetricsError::Status400),

            500 => Some(GetVolumeMetricsError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetVolumeMetricsError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
