/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed successes of method [`queue_email`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum QueueEmailSuccess {
    Status202(models::AsyncSendResponse),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for QueueEmailSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("QueueEmailSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`send_email`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum SendEmailSuccess {
    Status200(models::Message),
    Status202(models::SendResults),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for SendEmailSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SendEmailSuccess { [REDACTED] }")
    }
}

/// struct for typed errors of method [`queue_email`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum QueueEmailError {
    Status400(models::ErrorResponse),
    Status403(models::ErrorResponse),
    Status413(models::ErrorResponse),
    Status500(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for QueueEmailError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("QueueEmailError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`send_email`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum SendEmailError {
    Status400(models::ErrorResponse),
    Status403(models::ErrorResponse),
    Status413(models::ErrorResponse),
    Status500(models::ErrorResponse),
    Status502(models::ErrorResponse),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for SendEmailError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SendEmailError { [REDACTED] }")
    }
}

/// Queues an email message for asynchronous processing and returns immediately with a request ID.  The email will be processed in the background, and you'll receive webhook events for all delivery status updates (e.g. dropped, processed, delivered, hard-bounced). These webhook events are identical to those sent for the synchronous /send endpoint.  Use this endpoint when you need to send emails without waiting for processing to complete. This can improve your application's response time, especially when sending to multiple recipients.
pub async fn queue_email(
    configuration: &configuration::Configuration,
    x_api_key: &str,
    mail_send_body: models::MailSendBody,
) -> Result<ResponseContent<QueueEmailSuccess>, Error<QueueEmailError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;
    let p_body_mail_send_body = mail_send_body;

    let uri_str = format!("{}/send-async", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());
    req_builder = req_builder.json(&p_body_mail_send_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            202 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(QueueEmailSuccess::Status202(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(QueueEmailSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(QueueEmailError::Status400),

            403 => serde_json::from_str(&content)
                .ok()
                .map(QueueEmailError::Status403),

            413 => serde_json::from_str(&content)
                .ok()
                .map(QueueEmailError::Status413),

            500 => serde_json::from_str(&content)
                .ok()
                .map(QueueEmailError::Status500),

            _ => serde_json::from_str(&content)
                .ok()
                .map(QueueEmailError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Sends an email message to one or more recipients.  **Click Tracking Notes:** Only links (`<a>` tags) meeting all of the following conditions are processed for click tracking: - The URL is non-empty. - The URL starts with \"http\" or \"https\". - The link does not have a clicktracking attribute set to 'off'.
pub async fn send_email(
    configuration: &configuration::Configuration,
    x_api_key: &str,
    mail_send_body: models::MailSendBody,
    dry_run: Option<bool>,
) -> Result<ResponseContent<SendEmailSuccess>, Error<SendEmailError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;
    let p_body_mail_send_body = mail_send_body;
    let p_query_dry_run = dry_run;

    let uri_str = format!("{}/send", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref param_value) = p_query_dry_run {
        req_builder = req_builder.query(&[("dry-run", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());
    req_builder = req_builder.json(&p_body_mail_send_body);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(SendEmailSuccess::Status200(serde_json::from_str(&content)?))
                }
            }

            202 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(SendEmailSuccess::Status202(serde_json::from_str(&content)?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(SendEmailSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(SendEmailError::Status400),

            403 => serde_json::from_str(&content)
                .ok()
                .map(SendEmailError::Status403),

            413 => serde_json::from_str(&content)
                .ok()
                .map(SendEmailError::Status413),

            500 => serde_json::from_str(&content)
                .ok()
                .map(SendEmailError::Status500),

            502 => serde_json::from_str(&content)
                .ok()
                .map(SendEmailError::Status502),

            _ => serde_json::from_str(&content)
                .ok()
                .map(SendEmailError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
