/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed successes of method [`activate_subaccount`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ActivateSubaccountSuccess {
    Status204(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ActivateSubaccountSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ActivateSubaccountSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`create_subaccount`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CreateSubaccountSuccess {
    Status201(models::SubAccountDetails),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CreateSubaccountSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CreateSubaccountSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`create_subaccount_api_key`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CreateSubaccountApiKeySuccess {
    Status201(models::ApiKey),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CreateSubaccountApiKeySuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CreateSubaccountApiKeySuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`create_subaccount_smtp_password`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CreateSubaccountSmtpPasswordSuccess {
    Status201(models::SmtpPassword),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CreateSubaccountSmtpPasswordSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CreateSubaccountSmtpPasswordSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`delete_subaccount`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum DeleteSubaccountSuccess {
    Status204(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for DeleteSubaccountSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DeleteSubaccountSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`delete_subaccount_api_key`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum DeleteSubaccountApiKeySuccess {
    Status204(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for DeleteSubaccountApiKeySuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DeleteSubaccountApiKeySuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`delete_subaccount_limit`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum DeleteSubaccountLimitSuccess {
    Status204(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for DeleteSubaccountLimitSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DeleteSubaccountLimitSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`delete_subaccount_smtp_password`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum DeleteSubaccountSmtpPasswordSuccess {
    Status204(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for DeleteSubaccountSmtpPasswordSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DeleteSubaccountSmtpPasswordSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`get_subaccount_limit`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetSubaccountLimitSuccess {
    Status200(models::Limit),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetSubaccountLimitSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetSubaccountLimitSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`get_subaccount_usage`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetSubaccountUsageSuccess {
    Status200(models::UsageStats),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetSubaccountUsageSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetSubaccountUsageSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`list_subaccount_api_keys`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListSubaccountApiKeysSuccess {
    Status200(Vec<models::ApiKey>),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListSubaccountApiKeysSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListSubaccountApiKeysSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`list_subaccount_smtp_passwords`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListSubaccountSmtpPasswordsSuccess {
    Status200(Vec<models::SmtpPassword>),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListSubaccountSmtpPasswordsSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListSubaccountSmtpPasswordsSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`list_subaccounts`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListSubaccountsSuccess {
    Status200(Vec<models::SubAccountDetails>),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListSubaccountsSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListSubaccountsSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`set_subaccount_limit`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum SetSubaccountLimitSuccess {
    Status200(models::LimitUpdateResult),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for SetSubaccountLimitSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SetSubaccountLimitSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`suspend_subaccount`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum SuspendSubaccountSuccess {
    Status204(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for SuspendSubaccountSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SuspendSubaccountSuccess { [REDACTED] }")
    }
}

/// struct for typed errors of method [`activate_subaccount`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ActivateSubaccountError {
    Status403(),
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ActivateSubaccountError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ActivateSubaccountError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`create_subaccount`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CreateSubaccountError {
    Status400(),
    Status403(),
    Status409(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CreateSubaccountError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CreateSubaccountError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`create_subaccount_api_key`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CreateSubaccountApiKeyError {
    Status403(),
    Status404(),
    Status422(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CreateSubaccountApiKeyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CreateSubaccountApiKeyError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`create_subaccount_smtp_password`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CreateSubaccountSmtpPasswordError {
    Status403(),
    Status404(),
    Status422(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CreateSubaccountSmtpPasswordError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CreateSubaccountSmtpPasswordError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`delete_subaccount`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum DeleteSubaccountError {
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for DeleteSubaccountError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DeleteSubaccountError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`delete_subaccount_api_key`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum DeleteSubaccountApiKeyError {
    Status400(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for DeleteSubaccountApiKeyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DeleteSubaccountApiKeyError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`delete_subaccount_limit`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum DeleteSubaccountLimitError {
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for DeleteSubaccountLimitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DeleteSubaccountLimitError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`delete_subaccount_smtp_password`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum DeleteSubaccountSmtpPasswordError {
    Status400(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for DeleteSubaccountSmtpPasswordError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DeleteSubaccountSmtpPasswordError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`get_subaccount_limit`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetSubaccountLimitError {
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetSubaccountLimitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetSubaccountLimitError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`get_subaccount_usage`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetSubaccountUsageError {
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetSubaccountUsageError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetSubaccountUsageError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`list_subaccount_api_keys`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListSubaccountApiKeysError {
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListSubaccountApiKeysError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListSubaccountApiKeysError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`list_subaccount_smtp_passwords`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListSubaccountSmtpPasswordsError {
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListSubaccountSmtpPasswordsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListSubaccountSmtpPasswordsError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`list_subaccounts`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListSubaccountsError {
    Status400(models::ErrorResponse),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListSubaccountsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListSubaccountsError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`set_subaccount_limit`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum SetSubaccountLimitError {
    Status400(),
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for SetSubaccountLimitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SetSubaccountLimitError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`suspend_subaccount`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum SuspendSubaccountError {
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for SuspendSubaccountError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SuspendSubaccountError { [REDACTED] }")
    }
}

/// Activates a suspended sub-account identified by its handle, restoring its ability to send emails.
pub async fn activate_subaccount(
    configuration: &configuration::Configuration,
    handle: &str,
    x_api_key: &str,
) -> Result<ResponseContent<ActivateSubaccountSuccess>, Error<ActivateSubaccountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_handle = handle;
    let p_header_x_api_key = x_api_key;

    let uri_str = format!(
        "{}/sub-account/{handle}/activate",
        configuration.base_path,
        handle = crate::apis::urlencode(p_path_handle)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            204 => Some(ActivateSubaccountSuccess::Status204()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(ActivateSubaccountSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            403 => Some(ActivateSubaccountError::Status403()),

            404 => Some(ActivateSubaccountError::Status404()),

            500 => Some(ActivateSubaccountError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(ActivateSubaccountError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Creates a new sub-account under the parent account. Each sub-account must have a unique handle composed solely of lowercase alphanumeric characters. If no handle is provided, a random handle will be generated.
pub async fn create_subaccount(
    configuration: &configuration::Configuration,
    x_api_key: &str,
    sub_account_data: Option<models::SubAccountData>,
) -> Result<ResponseContent<CreateSubaccountSuccess>, Error<CreateSubaccountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;
    let p_body_sub_account_data = sub_account_data;

    let uri_str = format!("{}/sub-account", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());
    if let Some(ref body) = p_body_sub_account_data {
        req_builder = req_builder.json(body);
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            201 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(CreateSubaccountSuccess::Status201(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(CreateSubaccountSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => Some(CreateSubaccountError::Status400()),

            403 => Some(CreateSubaccountError::Status403()),

            409 => Some(CreateSubaccountError::Status409()),

            500 => Some(CreateSubaccountError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(CreateSubaccountError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Creates a new API key for the specified sub-account.
pub async fn create_subaccount_api_key(
    configuration: &configuration::Configuration,
    handle: &str,
    x_api_key: &str,
) -> Result<ResponseContent<CreateSubaccountApiKeySuccess>, Error<CreateSubaccountApiKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_handle = handle;
    let p_header_x_api_key = x_api_key;

    let uri_str = format!(
        "{}/sub-account/{handle}/api-key",
        configuration.base_path,
        handle = crate::apis::urlencode(p_path_handle)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            201 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(CreateSubaccountApiKeySuccess::Status201(
                        serde_json::from_str(&content)?,
                    ))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(CreateSubaccountApiKeySuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            403 => Some(CreateSubaccountApiKeyError::Status403()),

            404 => Some(CreateSubaccountApiKeyError::Status404()),

            422 => Some(CreateSubaccountApiKeyError::Status422()),

            500 => Some(CreateSubaccountApiKeyError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(CreateSubaccountApiKeyError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Creates a new SMTP password for the specified sub-account.
pub async fn create_subaccount_smtp_password(
    configuration: &configuration::Configuration,
    handle: &str,
    x_api_key: &str,
) -> Result<
    ResponseContent<CreateSubaccountSmtpPasswordSuccess>,
    Error<CreateSubaccountSmtpPasswordError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_handle = handle;
    let p_header_x_api_key = x_api_key;

    let uri_str = format!(
        "{}/sub-account/{handle}/smtp-password",
        configuration.base_path,
        handle = crate::apis::urlencode(p_path_handle)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            201 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(CreateSubaccountSmtpPasswordSuccess::Status201(
                        serde_json::from_str(&content)?,
                    ))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(CreateSubaccountSmtpPasswordSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            403 => Some(CreateSubaccountSmtpPasswordError::Status403()),

            404 => Some(CreateSubaccountSmtpPasswordError::Status404()),

            422 => Some(CreateSubaccountSmtpPasswordError::Status422()),

            500 => Some(CreateSubaccountSmtpPasswordError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(CreateSubaccountSmtpPasswordError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Deletes the sub-account identified by its handle.
pub async fn delete_subaccount(
    configuration: &configuration::Configuration,
    handle: &str,
    x_api_key: &str,
) -> Result<ResponseContent<DeleteSubaccountSuccess>, Error<DeleteSubaccountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_handle = handle;
    let p_header_x_api_key = x_api_key;

    let uri_str = format!(
        "{}/sub-account/{handle}",
        configuration.base_path,
        handle = crate::apis::urlencode(p_path_handle)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            204 => Some(DeleteSubaccountSuccess::Status204()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(DeleteSubaccountSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            500 => Some(DeleteSubaccountError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(DeleteSubaccountError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Deletes the API key identified by its ID for the specified sub-account.
pub async fn delete_subaccount_api_key(
    configuration: &configuration::Configuration,
    handle: &str,
    id: i32,
    x_api_key: &str,
) -> Result<ResponseContent<DeleteSubaccountApiKeySuccess>, Error<DeleteSubaccountApiKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_handle = handle;
    let p_path_id = id;
    let p_header_x_api_key = x_api_key;

    let uri_str = format!(
        "{}/sub-account/{handle}/api-key/{id}",
        configuration.base_path,
        handle = crate::apis::urlencode(p_path_handle),
        id = p_path_id
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            204 => Some(DeleteSubaccountApiKeySuccess::Status204()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(DeleteSubaccountApiKeySuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => Some(DeleteSubaccountApiKeyError::Status400()),

            500 => Some(DeleteSubaccountApiKeyError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(DeleteSubaccountApiKeyError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Deletes the limit for the specified sub-account. After a successful deletion, the specified sub-account will be limited to the parent account's limit.
pub async fn delete_subaccount_limit(
    configuration: &configuration::Configuration,
    handle: &str,
    x_api_key: &str,
) -> Result<ResponseContent<DeleteSubaccountLimitSuccess>, Error<DeleteSubaccountLimitError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_handle = handle;
    let p_header_x_api_key = x_api_key;

    let uri_str = format!(
        "{}/sub-account/{handle}/limit",
        configuration.base_path,
        handle = crate::apis::urlencode(p_path_handle)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            204 => Some(DeleteSubaccountLimitSuccess::Status204()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(DeleteSubaccountLimitSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            500 => Some(DeleteSubaccountLimitError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(DeleteSubaccountLimitError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Deletes the SMTP password identified by its ID for the specified sub-account.
pub async fn delete_subaccount_smtp_password(
    configuration: &configuration::Configuration,
    handle: &str,
    id: i32,
    x_api_key: &str,
) -> Result<
    ResponseContent<DeleteSubaccountSmtpPasswordSuccess>,
    Error<DeleteSubaccountSmtpPasswordError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_handle = handle;
    let p_path_id = id;
    let p_header_x_api_key = x_api_key;

    let uri_str = format!(
        "{}/sub-account/{handle}/smtp-password/{id}",
        configuration.base_path,
        handle = crate::apis::urlencode(p_path_handle),
        id = p_path_id
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            204 => Some(DeleteSubaccountSmtpPasswordSuccess::Status204()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(DeleteSubaccountSmtpPasswordSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => Some(DeleteSubaccountSmtpPasswordError::Status400()),

            500 => Some(DeleteSubaccountSmtpPasswordError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(DeleteSubaccountSmtpPasswordError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves the limit of a specified sub-account. A value of -1 indicates that the sub-account inherits the parent account's limit, allowing the sub-account to utilize any remaining capacity within the parent account's allocation.
pub async fn get_subaccount_limit(
    configuration: &configuration::Configuration,
    handle: &str,
    x_api_key: &str,
) -> Result<ResponseContent<GetSubaccountLimitSuccess>, Error<GetSubaccountLimitError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_handle = handle;
    let p_header_x_api_key = x_api_key;

    let uri_str = format!(
        "{}/sub-account/{handle}/limit",
        configuration.base_path,
        handle = crate::apis::urlencode(p_path_handle)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(GetSubaccountLimitSuccess::Status200(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetSubaccountLimitSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            404 => Some(GetSubaccountLimitError::Status404()),

            500 => Some(GetSubaccountLimitError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetSubaccountLimitError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves usage statistics for the specified sub-account during the current billing period.
pub async fn get_subaccount_usage(
    configuration: &configuration::Configuration,
    handle: &str,
    x_api_key: &str,
) -> Result<ResponseContent<GetSubaccountUsageSuccess>, Error<GetSubaccountUsageError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_handle = handle;
    let p_header_x_api_key = x_api_key;

    let uri_str = format!(
        "{}/sub-account/{handle}/usage",
        configuration.base_path,
        handle = crate::apis::urlencode(p_path_handle)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(GetSubaccountUsageSuccess::Status200(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetSubaccountUsageSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            404 => Some(GetSubaccountUsageError::Status404()),

            500 => Some(GetSubaccountUsageError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetSubaccountUsageError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves details of all API keys associated with the specified sub-account. For security reasons, the full API key is **not** returned; only the key ID and a partially redacted version are provided.
pub async fn list_subaccount_api_keys(
    configuration: &configuration::Configuration,
    handle: &str,
    x_api_key: &str,
    limit: Option<i32>,
    offset: Option<i32>,
) -> Result<ResponseContent<ListSubaccountApiKeysSuccess>, Error<ListSubaccountApiKeysError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_handle = handle;
    let p_header_x_api_key = x_api_key;
    let p_query_limit = limit;
    let p_query_offset = offset;

    let uri_str = format!(
        "{}/sub-account/{handle}/api-key",
        configuration.base_path,
        handle = crate::apis::urlencode(p_path_handle)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(ListSubaccountApiKeysSuccess::Status200(
                        serde_json::from_str(&content)?,
                    ))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListSubaccountApiKeysSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            404 => Some(ListSubaccountApiKeysError::Status404()),

            500 => Some(ListSubaccountApiKeysError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListSubaccountApiKeysError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves details of all SMTP passwords associated with the specified sub-account. For security, the full SMTP password is **not** returned; only the password ID and a partially redacted version are provided.
pub async fn list_subaccount_smtp_passwords(
    configuration: &configuration::Configuration,
    handle: &str,
    x_api_key: &str,
) -> Result<
    ResponseContent<ListSubaccountSmtpPasswordsSuccess>,
    Error<ListSubaccountSmtpPasswordsError>,
> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_handle = handle;
    let p_header_x_api_key = x_api_key;

    let uri_str = format!(
        "{}/sub-account/{handle}/smtp-password",
        configuration.base_path,
        handle = crate::apis::urlencode(p_path_handle)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(ListSubaccountSmtpPasswordsSuccess::Status200(
                        serde_json::from_str(&content)?,
                    ))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListSubaccountSmtpPasswordsSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            404 => Some(ListSubaccountSmtpPasswordsError::Status404()),

            500 => Some(ListSubaccountSmtpPasswordsError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListSubaccountSmtpPasswordsError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves all sub-accounts associated with the parent account. The response is paginated with a default limit of 1000 sub-accounts per page and an offset of 0.
pub async fn list_subaccounts(
    configuration: &configuration::Configuration,
    x_api_key: &str,
    limit: Option<i32>,
    offset: Option<i32>,
) -> Result<ResponseContent<ListSubaccountsSuccess>, Error<ListSubaccountsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;
    let p_query_limit = limit;
    let p_query_offset = offset;

    let uri_str = format!("{}/sub-account", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(ListSubaccountsSuccess::Status200(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListSubaccountsSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(ListSubaccountsError::Status400),

            500 => Some(ListSubaccountsError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListSubaccountsError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Sets the limit for the specified sub-account. The minimum allowed sends is 0.
pub async fn set_subaccount_limit(
    configuration: &configuration::Configuration,
    handle: &str,
    x_api_key: &str,
    limit_input: models::LimitInput,
) -> Result<ResponseContent<SetSubaccountLimitSuccess>, Error<SetSubaccountLimitError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_handle = handle;
    let p_header_x_api_key = x_api_key;
    let p_body_limit_input = limit_input;

    let uri_str = format!(
        "{}/sub-account/{handle}/limit",
        configuration.base_path,
        handle = crate::apis::urlencode(p_path_handle)
    );
    let mut req_builder = configuration.client.request(reqwest::Method::PUT, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());
    req_builder = req_builder.json(&p_body_limit_input);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(SetSubaccountLimitSuccess::Status200(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(SetSubaccountLimitSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => Some(SetSubaccountLimitError::Status400()),

            404 => Some(SetSubaccountLimitError::Status404()),

            500 => Some(SetSubaccountLimitError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(SetSubaccountLimitError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Suspends the sub-account identified by its handle. This action disables the account, preventing it from sending any emails until it is reactivated.
pub async fn suspend_subaccount(
    configuration: &configuration::Configuration,
    handle: &str,
    x_api_key: &str,
) -> Result<ResponseContent<SuspendSubaccountSuccess>, Error<SuspendSubaccountError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_handle = handle;
    let p_header_x_api_key = x_api_key;

    let uri_str = format!(
        "{}/sub-account/{handle}/suspend",
        configuration.base_path,
        handle = crate::apis::urlencode(p_path_handle)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            204 => Some(SuspendSubaccountSuccess::Status204()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(SuspendSubaccountSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            404 => Some(SuspendSubaccountError::Status404()),

            500 => Some(SuspendSubaccountError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(SuspendSubaccountError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
