/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed successes of method [`create_suppressions`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CreateSuppressionsSuccess {
    Status201(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CreateSuppressionsSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CreateSuppressionsSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`delete_suppression`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum DeleteSuppressionSuccess {
    Status204(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for DeleteSuppressionSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DeleteSuppressionSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`list_suppressions`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListSuppressionsSuccess {
    Status200(models::SuppressionListResponse),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListSuppressionsSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListSuppressionsSuccess { [REDACTED] }")
    }
}

/// struct for typed errors of method [`create_suppressions`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CreateSuppressionsError {
    Status400(models::ErrorResponse),
    Status409(),
    Status413(),
    Status500(),
    Status503(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CreateSuppressionsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CreateSuppressionsError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`delete_suppression`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum DeleteSuppressionError {
    Status400(models::ErrorResponse),
    Status500(),
    Status503(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for DeleteSuppressionError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DeleteSuppressionError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`list_suppressions`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListSuppressionsError {
    Status400(models::ErrorResponse),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListSuppressionsError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListSuppressionsError { [REDACTED] }")
    }
}

/// Creates suppression entries for the specified account. Parent accounts can create suppression entries for all associated sub-accounts. If suppression_type is not provided, it defaults to 'non-transactional'. The operation is atomic, meaning all entries are successfully added or none are added if an error occurs.
pub async fn create_suppressions(
    configuration: &configuration::Configuration,
    x_api_key: &str,
    suppression_list_input: models::SuppressionListInput,
) -> Result<ResponseContent<CreateSuppressionsSuccess>, Error<CreateSuppressionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;
    let p_body_suppression_list_input = suppression_list_input;

    let uri_str = format!("{}/suppression-list", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());
    req_builder = req_builder.json(&p_body_suppression_list_input);

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            201 => Some(CreateSuppressionsSuccess::Status201()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(CreateSuppressionsSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(CreateSuppressionsError::Status400),

            409 => Some(CreateSuppressionsError::Status409()),

            413 => Some(CreateSuppressionsError::Status413()),

            500 => Some(CreateSuppressionsError::Status500()),

            503 => Some(CreateSuppressionsError::Status503()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(CreateSuppressionsError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Deletes suppression entry associated with the account based on the specified recipient and source. If source is not provided, it defaults to 'api'. If source is set to 'all', all suppression entries related to the specified recipient will be deleted.
pub async fn delete_suppression(
    configuration: &configuration::Configuration,
    recipient: &str,
    x_api_key: &str,
    source: Option<&str>,
) -> Result<ResponseContent<DeleteSuppressionSuccess>, Error<DeleteSuppressionError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_recipient = recipient;
    let p_header_x_api_key = x_api_key;
    let p_query_source = source;

    let uri_str = format!(
        "{}/suppression-list/recipients/{recipient}",
        configuration.base_path,
        recipient = crate::apis::urlencode(p_path_recipient)
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref param_value) = p_query_source {
        req_builder = req_builder.query(&[("source", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            204 => Some(DeleteSuppressionSuccess::Status204()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(DeleteSuppressionSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(DeleteSuppressionError::Status400),

            500 => Some(DeleteSuppressionError::Status500()),

            503 => Some(DeleteSuppressionError::Status503()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(DeleteSuppressionError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieve suppression entries associated with the specified account. Supports filtering by recipient, source and creation date range. The response is paginated, with a default limit of 1000 entries per page and an offset of 0.
pub async fn list_suppressions(
    configuration: &configuration::Configuration,
    x_api_key: &str,
    recipient: Option<&str>,
    source: Option<&str>,
    created_before: Option<&str>,
    created_after: Option<&str>,
    limit: Option<i32>,
    offset: Option<i32>,
) -> Result<ResponseContent<ListSuppressionsSuccess>, Error<ListSuppressionsError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;
    let p_query_recipient = recipient;
    let p_query_source = source;
    let p_query_created_before = created_before;
    let p_query_created_after = created_after;
    let p_query_limit = limit;
    let p_query_offset = offset;

    let uri_str = format!("{}/suppression-list", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_recipient {
        req_builder = req_builder.query(&[("recipient", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_source {
        req_builder = req_builder.query(&[("source", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_created_before {
        req_builder = req_builder.query(&[("created_before", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_created_after {
        req_builder = req_builder.query(&[("created_after", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(ListSuppressionsSuccess::Status200(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListSuppressionsSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(ListSuppressionsError::Status400),

            500 => Some(ListSuppressionsError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListSuppressionsError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
