/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed successes of method [`get_usage`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetUsageSuccess {
    Status200(models::UsageStats),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetUsageSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetUsageSuccess { [REDACTED] }")
    }
}

/// struct for typed errors of method [`get_usage`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetUsageError {
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetUsageError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetUsageError { [REDACTED] }")
    }
}

/// Retrieves usage statistics during the current billing period.
pub async fn get_usage(
    configuration: &configuration::Configuration,
    x_api_key: &str,
) -> Result<ResponseContent<GetUsageSuccess>, Error<GetUsageError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;

    let uri_str = format!("{}/usage", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(GetUsageSuccess::Status200(serde_json::from_str(&content)?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetUsageSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            500 => Some(GetUsageError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetUsageError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
