/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, ContentType, Error};
use crate::{apis::ResponseContent, models};
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};

/// struct for typed successes of method [`create_webhook`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CreateWebhookSuccess {
    Status201(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CreateWebhookSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CreateWebhookSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`delete_webhooks`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum DeleteWebhooksSuccess {
    Status204(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for DeleteWebhooksSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DeleteWebhooksSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`get_webhook_signing_key`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetWebhookSigningKeySuccess {
    Status200(models::Key),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetWebhookSigningKeySuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetWebhookSigningKeySuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`list_webhook_batches`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListWebhookBatchesSuccess {
    Status200(models::WebhookBatchResult),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListWebhookBatchesSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListWebhookBatchesSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`list_webhooks`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListWebhooksSuccess {
    Status200(Vec<models::Webhook>),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListWebhooksSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListWebhooksSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`resend_webhook_batch`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ResendWebhookBatchSuccess {
    Status200(models::WebhookResendResponse),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ResendWebhookBatchSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ResendWebhookBatchSuccess { [REDACTED] }")
    }
}

/// struct for typed successes of method [`validate_webhook`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ValidateWebhookSuccess {
    Status200(models::WebhookValidationResults),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ValidateWebhookSuccess {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ValidateWebhookSuccess { [REDACTED] }")
    }
}

/// struct for typed errors of method [`create_webhook`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum CreateWebhookError {
    Status400(),
    Status409(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for CreateWebhookError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CreateWebhookError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`delete_webhooks`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum DeleteWebhooksError {
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for DeleteWebhooksError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DeleteWebhooksError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`get_webhook_signing_key`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum GetWebhookSigningKeyError {
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for GetWebhookSigningKeyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("GetWebhookSigningKeyError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`list_webhook_batches`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListWebhookBatchesError {
    Status400(models::ErrorResponse),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListWebhookBatchesError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListWebhookBatchesError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`list_webhooks`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ListWebhooksError {
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ListWebhooksError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ListWebhooksError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`resend_webhook_batch`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ResendWebhookBatchError {
    Status400(),
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ResendWebhookBatchError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ResendWebhookBatchError { [REDACTED] }")
    }
}

/// struct for typed errors of method [`validate_webhook`]
#[derive(Clone, Serialize)]
#[serde(untagged)]
pub enum ValidateWebhookError {
    Status400(models::ErrorResponse),
    Status404(),
    Status500(),
    UnknownValue(serde_json::Value),
}

impl std::fmt::Debug for ValidateWebhookError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ValidateWebhookError { [REDACTED] }")
    }
}

/// Enrolls the customer to receive event notifications via webhooks.
pub async fn create_webhook(
    configuration: &configuration::Configuration,
    endpoint: &str,
    x_api_key: &str,
) -> Result<ResponseContent<CreateWebhookSuccess>, Error<CreateWebhookError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_endpoint = endpoint;
    let p_header_x_api_key = x_api_key;

    let uri_str = format!("{}/webhook", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    req_builder = req_builder.query(&[("endpoint", &p_query_endpoint.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            201 => Some(CreateWebhookSuccess::Status201()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(CreateWebhookSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => Some(CreateWebhookError::Status400()),

            409 => Some(CreateWebhookError::Status409()),

            500 => Some(CreateWebhookError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(CreateWebhookError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Deletes all registered webhook endpoints for the customer.
pub async fn delete_webhooks(
    configuration: &configuration::Configuration,
    x_api_key: &str,
) -> Result<ResponseContent<DeleteWebhooksSuccess>, Error<DeleteWebhooksError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;

    let uri_str = format!("{}/webhook", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::DELETE, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            204 => Some(DeleteWebhooksSuccess::Status204()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(DeleteWebhooksSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            500 => Some(DeleteWebhooksError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(DeleteWebhooksError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves the public key used to verify signatures on incoming webhook payloads.
pub async fn get_webhook_signing_key(
    configuration: &configuration::Configuration,
    id: &str,
) -> Result<ResponseContent<GetWebhookSigningKeySuccess>, Error<GetWebhookSigningKeyError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_query_id = id;

    let uri_str = format!("{}/webhook/public-key", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    req_builder = req_builder.query(&[("id", &p_query_id.to_string())]);
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(GetWebhookSigningKeySuccess::Status200(
                        serde_json::from_str(&content)?,
                    ))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetWebhookSigningKeySuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            404 => Some(GetWebhookSigningKeyError::Status404()),

            500 => Some(GetWebhookSigningKeyError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(GetWebhookSigningKeyError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves paged webhook batches associated with the customer. The time range specified by created_after and created_before filters must not exceed 31 days. If neither is specified, the default time range is the last 3 days. Optional filters include status categories, webhook, limit and offset.
pub async fn list_webhook_batches(
    configuration: &configuration::Configuration,
    x_api_key: &str,
    created_after: Option<&str>,
    created_before: Option<&str>,
    statuses: Option<Vec<String>>,
    webhook: Option<&str>,
    limit: Option<i32>,
    offset: Option<i32>,
) -> Result<ResponseContent<ListWebhookBatchesSuccess>, Error<ListWebhookBatchesError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;
    let p_query_created_after = created_after;
    let p_query_created_before = created_before;
    let p_query_statuses = statuses;
    let p_query_webhook = webhook;
    let p_query_limit = limit;
    let p_query_offset = offset;

    let uri_str = format!("{}/webhook-batch", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref param_value) = p_query_created_after {
        req_builder = req_builder.query(&[("created_after", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_created_before {
        req_builder = req_builder.query(&[("created_before", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_statuses {
        req_builder = match "csv" {
            "multi" => req_builder.query(
                &param_value
                    .iter()
                    .map(|p| ("statuses".to_owned(), p.to_string()))
                    .collect::<Vec<(std::string::String, std::string::String)>>(),
            ),
            _ => req_builder.query(&[(
                "statuses",
                &param_value
                    .iter()
                    .map(|p| p.to_string())
                    .collect::<Vec<String>>()
                    .join(",")
                    .to_string(),
            )]),
        };
    }
    if let Some(ref param_value) = p_query_webhook {
        req_builder = req_builder.query(&[("webhook", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_limit {
        req_builder = req_builder.query(&[("limit", &param_value.to_string())]);
    }
    if let Some(ref param_value) = p_query_offset {
        req_builder = req_builder.query(&[("offset", &param_value.to_string())]);
    }
    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(ListWebhookBatchesSuccess::Status200(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListWebhookBatchesSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(ListWebhookBatchesError::Status400),

            500 => Some(ListWebhookBatchesError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListWebhookBatchesError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Retrieves all registered webhook endpoints associated with the customer.
pub async fn list_webhooks(
    configuration: &configuration::Configuration,
    x_api_key: &str,
) -> Result<ResponseContent<ListWebhooksSuccess>, Error<ListWebhooksError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;

    let uri_str = format!("{}/webhook", configuration.base_path);
    let mut req_builder = configuration.client.request(reqwest::Method::GET, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(ListWebhooksSuccess::Status200(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListWebhooksSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            500 => Some(ListWebhooksError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(ListWebhooksError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Synchronously resend the webhook batch with the provided batch_id for the customer. The result is returned in the response.
pub async fn resend_webhook_batch(
    configuration: &configuration::Configuration,
    batch_id: i64,
    x_api_key: &str,
) -> Result<ResponseContent<ResendWebhookBatchSuccess>, Error<ResendWebhookBatchError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_path_batch_id = batch_id;
    let p_header_x_api_key = x_api_key;

    let uri_str = format!(
        "{}/webhook-batch/{batch_id}/resend",
        configuration.base_path,
        batch_id = p_path_batch_id
    );
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(ResendWebhookBatchSuccess::Status200(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(ResendWebhookBatchSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => Some(ResendWebhookBatchError::Status400()),

            404 => Some(ResendWebhookBatchError::Status404()),

            500 => Some(ResendWebhookBatchError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(ResendWebhookBatchError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}

/// Validates whether your enrolled webhook(s) respond with an HTTP 2xx status code. Sends a test request to each webhook containing your customer handle, a hardcoded event type(test), a hardcoded sender email(test@mailchannels.com),a timestamp, a request ID (provided or generated), and an SMTP ID. The response includes the HTTP status code and body returned by each webhook.
pub async fn validate_webhook(
    configuration: &configuration::Configuration,
    x_api_key: &str,
    webhook_validation_request_body: Option<models::WebhookValidationRequestBody>,
) -> Result<ResponseContent<ValidateWebhookSuccess>, Error<ValidateWebhookError>> {
    // add a prefix to parameters to efficiently prevent name collisions
    let p_header_x_api_key = x_api_key;
    let p_body_webhook_validation_request_body = webhook_validation_request_body;

    let uri_str = format!("{}/webhook/validate", configuration.base_path);
    let mut req_builder = configuration
        .client
        .request(reqwest::Method::POST, &uri_str);

    if let Some(ref user_agent) = configuration.user_agent {
        req_builder = req_builder.header(reqwest::header::USER_AGENT, user_agent.clone());
    }
    req_builder = req_builder.header("X-Api-Key", p_header_x_api_key.to_string());
    if let Some(ref body) = p_body_webhook_validation_request_body {
        req_builder = req_builder.json(body);
    }

    let req = req_builder.build()?;
    let resp = configuration.client.execute(req).await?;

    let status = resp.status();

    if status.is_success() {
        let content = resp.text().await?;
        // HTTP status selects the response schema; shapes may overlap.
        let entity = match status.as_u16() {
            200 => {
                if content.trim().is_empty() {
                    None
                } else {
                    Some(ValidateWebhookSuccess::Status200(serde_json::from_str(
                        &content,
                    )?))
                }
            }

            _ => serde_json::from_str(&content)
                .ok()
                .map(ValidateWebhookSuccess::UnknownValue),
        };
        Ok(ResponseContent {
            status,
            content,
            entity,
        })
    } else {
        let content = resp.text().await?;
        let entity = match status.as_u16() {
            400 => serde_json::from_str(&content)
                .ok()
                .map(ValidateWebhookError::Status400),

            404 => Some(ValidateWebhookError::Status404()),

            500 => Some(ValidateWebhookError::Status500()),

            _ => serde_json::from_str(&content)
                .ok()
                .map(ValidateWebhookError::UnknownValue),
        };
        Err(Error::ResponseError(ResponseContent {
            status,
            content,
            entity,
        }))
    }
}
