/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AsyncSendResponse {
    /// ISO 8601 timestamp when the request was queued for processing.
    #[serde(rename = "queued_at")]
    pub queued_at: chrono::DateTime<chrono::FixedOffset>,
    /// Unique identifier for tracking this async request. Will be included in all webhook events for this request.
    #[serde(rename = "request_id")]
    pub request_id: String,
}

impl AsyncSendResponse {
    pub fn new(
        queued_at: chrono::DateTime<chrono::FixedOffset>,
        request_id: String,
    ) -> AsyncSendResponse {
        AsyncSendResponse {
            queued_at,
            request_id,
        }
    }
}

impl std::fmt::Debug for AsyncSendResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("AsyncSendResponse { [REDACTED] }")
    }
}
