/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Attachment {
    /// the attachment data, encoded in base64
    #[serde(rename = "content")]
    pub content: String,
    /// A unique identifier for this attachment. When set, the attachment is embedded inline in the message body (Content-Disposition: inline) instead of offered as a downloadable attachment, and can be referenced from HTML content via a `cid:` URI, e.g. `<img src=\"cid:logo123\">` refers to an attachment with `content_id: logo123` (RFC 2392). Must be unique across all attachments in the request.
    #[serde(rename = "content_id", skip_serializing_if = "Option::is_none")]
    pub content_id: Option<String>,
    /// the name of the attachment file
    #[serde(rename = "filename")]
    pub filename: String,
    /// the MIME type of the attachment
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
}

impl Attachment {
    pub fn new(content: String, filename: String) -> Attachment {
        Attachment {
            content,
            content_id: None,
            filename,
            r#type: None,
        }
    }
}

impl std::fmt::Debug for Attachment {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("Attachment { [REDACTED] }")
    }
}
