/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CheckDomainBody {
    /// Each item may include DKIM domain, selector and private key. Up to 10 items are allowed. The absence or presence of these fields affects how DKIM settings are validated: 1. If dkim_domain, dkim_selector, and dkim_private_key are all present, verify using the provided domain, selector, and key. 2. If dkim_domain and dkim_selector are present, use the stored private key for the given domain and selector. 3. If only dkim_domain is present, use all stored keys for the given domain. 4. If none are present, use all stored keys for the domain provided in the `domain` field of the request. 5. If dkim_private_key is present, dkim_selector must be present. 6. If dkim_selector is present and dkim_domain is not, the domain will be taken from the `domain` field of the request.
    #[serde(rename = "dkim_settings", skip_serializing_if = "Option::is_none")]
    pub dkim_settings: Option<Vec<models::DkimSetting>>,
    /// Domain used for sending emails. If dkim_settings are not provided, or dkim_settings are provided with no dkim_domain, the stored dkim settings for this domain will be used.
    #[serde(rename = "domain")]
    pub domain: String,
    /// Optional envelope-from domain. During message delivery, SPF and Domain Lockdown verification are evaluated  against the envelope sender domain. If your envelope-from domain differs from the domain used for sending messages, provide it here to ensure both checks are run against the correct domain. Otherwise, SPF or Domain Lockdown failures may cause message delivery to fail.
    #[serde(
        rename = "envelope_from_domain",
        skip_serializing_if = "Option::is_none"
    )]
    pub envelope_from_domain: Option<String>,
    /// Used exclusively for [Domain Lockdown](https://support.mailchannels.com/hc/en-us/articles/16918954360845-Secure-your-domain-name-against-spoofing-with-Domain-Lockdown) verification. If you're not using `senderid` to associate your domain with your account, you can disregard this field. The corresponding value is included in the X-MailChannels-SenderId header of emails sent via MailChannels.
    #[serde(rename = "sender_id", skip_serializing_if = "Option::is_none")]
    pub sender_id: Option<String>,
}

impl CheckDomainBody {
    pub fn new(domain: String) -> CheckDomainBody {
        CheckDomainBody {
            dkim_settings: None,
            domain,
            envelope_from_domain: None,
            sender_id: None,
        }
    }
}

impl std::fmt::Debug for CheckDomainBody {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CheckDomainBody { [REDACTED] }")
    }
}
