/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ContentItem {
    /// The template type of the content
    #[serde(rename = "template_type", skip_serializing_if = "Option::is_none")]
    pub template_type: Option<TemplateType>,
    /// The mime type of the content you are including in your email
    #[serde(rename = "type")]
    pub r#type: String,
    /// The actual content of the specified mime type that you are including in the message
    #[serde(rename = "value")]
    pub value: String,
}

impl ContentItem {
    pub fn new(r#type: String, value: String) -> ContentItem {
        ContentItem {
            template_type: None,
            r#type,
            value,
        }
    }
}
/// The template type of the content
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TemplateType {
    #[serde(rename = "mustache")]
    Mustache,
}

impl Default for TemplateType {
    fn default() -> TemplateType {
        Self::Mustache
    }
}

impl std::fmt::Debug for ContentItem {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("ContentItem { [REDACTED] }")
    }
}
