/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CustomTrackingDomainListResponse {
    /// List of custom tracking domains matching the filter criteria
    #[serde(rename = "custom_tracking_domains")]
    pub custom_tracking_domains: Vec<models::CustomTrackingDomain>,
    /// Total number of custom tracking domains
    #[serde(rename = "total")]
    pub total: i32,
}

impl CustomTrackingDomainListResponse {
    pub fn new(
        custom_tracking_domains: Vec<models::CustomTrackingDomain>,
        total: i32,
    ) -> CustomTrackingDomainListResponse {
        CustomTrackingDomainListResponse {
            custom_tracking_domains,
            total,
        }
    }
}

impl std::fmt::Debug for CustomTrackingDomainListResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CustomTrackingDomainListResponse { [REDACTED] }")
    }
}
