/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct CustomTrackingDomain {
    /// ISO 8601 timestamp when the domain was registered
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// The registered domain hostname
    #[serde(rename = "hostname")]
    pub hostname: String,
    /// The label for this custom tracking domain
    #[serde(rename = "name")]
    pub name: String,
    /// The event type this domain handles
    #[serde(rename = "scope")]
    pub scope: Scope,
    /// Current status of the custom tracking domain
    #[serde(rename = "status")]
    pub status: Status,
}

impl CustomTrackingDomain {
    pub fn new(
        created_at: chrono::DateTime<chrono::FixedOffset>,
        hostname: String,
        name: String,
        scope: Scope,
        status: Status,
    ) -> CustomTrackingDomain {
        CustomTrackingDomain {
            created_at,
            hostname,
            name,
            scope,
            status,
        }
    }
}
/// The event type this domain handles
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scope {
    #[serde(rename = "click")]
    Click,
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "unsubscribe")]
    Unsubscribe,
}

impl Default for Scope {
    fn default() -> Scope {
        Self::Click
    }
}
/// Current status of the custom tracking domain
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "disabled")]
    Disabled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}

impl std::fmt::Debug for CustomTrackingDomain {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("CustomTrackingDomain { [REDACTED] }")
    }
}
