/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DkimKeyPairUpdateRequest {
    /// New status of the DKIM key pair
    #[serde(rename = "status")]
    pub status: Status,
}

impl DkimKeyPairUpdateRequest {
    pub fn new(status: Status) -> DkimKeyPairUpdateRequest {
        DkimKeyPairUpdateRequest { status }
    }
}
/// New status of the DKIM key pair
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "revoked")]
    Revoked,
    #[serde(rename = "retired")]
    Retired,
    #[serde(rename = "rotated")]
    Rotated,
}

impl Default for Status {
    fn default() -> Status {
        Self::Revoked
    }
}

impl std::fmt::Debug for DkimKeyPairUpdateRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DkimKeyPairUpdateRequest { [REDACTED] }")
    }
}
