/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DkimDnsRecord : Suggested DNS record for the DKIM key
#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DkimDnsRecord {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: String,
    #[serde(rename = "value")]
    pub value: String,
}

impl DkimDnsRecord {
    /// Suggested DNS record for the DKIM key
    pub fn new(name: String, r#type: String, value: String) -> DkimDnsRecord {
        DkimDnsRecord {
            name,
            r#type,
            value,
        }
    }
}

impl std::fmt::Debug for DkimDnsRecord {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DkimDnsRecord { [REDACTED] }")
    }
}
