/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DkimKeyPairCreateRequest {
    /// Algorithm used for the new key pair Currently, only RSA is supported.
    #[serde(rename = "algorithm", skip_serializing_if = "Option::is_none")]
    pub algorithm: Option<Algorithm>,
    /// Key length in bits. For RSA, must be a multiple of 1024. Common values: 1024 or 2048. Defaults to 2048 bits.
    #[serde(rename = "key_length", skip_serializing_if = "Option::is_none")]
    pub key_length: Option<i32>,
    /// Selector for the new key pair
    #[serde(rename = "selector")]
    pub selector: String,
}

impl DkimKeyPairCreateRequest {
    pub fn new(selector: String) -> DkimKeyPairCreateRequest {
        DkimKeyPairCreateRequest {
            algorithm: None,
            key_length: None,
            selector,
        }
    }
}
/// Algorithm used for the new key pair Currently, only RSA is supported.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Algorithm {
    #[serde(rename = "rsa")]
    Rsa,
}

impl Default for Algorithm {
    fn default() -> Algorithm {
        Self::Rsa
    }
}

impl std::fmt::Debug for DkimKeyPairCreateRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DkimKeyPairCreateRequest { [REDACTED] }")
    }
}
