/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DkimKeyInfo {
    /// Algorithm used for the key pair
    #[serde(rename = "algorithm")]
    pub algorithm: String,
    /// Timestamp when the key pair was created
    #[serde(
        rename = "created_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub created_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Suggested DNS records for the DKIM key
    #[serde(rename = "dkim_dns_records", skip_serializing_if = "Option::is_none")]
    pub dkim_dns_records: Option<Vec<models::DkimDnsRecord>>,
    /// Domain associated with the key pair
    #[serde(rename = "domain")]
    pub domain: String,
    /// UTC timestamp after which you can no longer use the rotated key for signing
    #[serde(
        rename = "gracePeriodExpiresAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub grace_period_expires_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Key length in bits
    #[serde(rename = "key_length", skip_serializing_if = "Option::is_none")]
    pub key_length: Option<i32>,
    #[serde(rename = "public_key")]
    pub public_key: String,
    /// UTC timestamp when a rotated key pair is retired
    #[serde(
        rename = "retiresAt",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub retires_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Selector assigned to the key pair
    #[serde(rename = "selector")]
    pub selector: String,
    #[serde(rename = "status")]
    pub status: Status,
    /// Timestamp when the key was last modified
    #[serde(
        rename = "status_modified_at",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status_modified_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
}

impl DkimKeyInfo {
    pub fn new(
        algorithm: String,
        domain: String,
        public_key: String,
        selector: String,
        status: Status,
    ) -> DkimKeyInfo {
        DkimKeyInfo {
            algorithm,
            created_at: None,
            dkim_dns_records: None,
            domain,
            grace_period_expires_at: None,
            key_length: None,
            public_key,
            retires_at: None,
            selector,
            status,
            status_modified_at: None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "retired")]
    Retired,
    #[serde(rename = "revoked")]
    Revoked,
    #[serde(rename = "rotated")]
    Rotated,
}

impl Default for Status {
    fn default() -> Status {
        Self::Active
    }
}

impl std::fmt::Debug for DkimKeyInfo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DkimKeyInfo { [REDACTED] }")
    }
}
