/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DkimKeyList {
    /// List of keys matching the filter. Empty if no keys match the filter.
    #[serde(rename = "keys")]
    pub keys: Vec<models::DkimKeyInfo>,
}

impl DkimKeyList {
    pub fn new(keys: Vec<models::DkimKeyInfo>) -> DkimKeyList {
        DkimKeyList { keys }
    }
}

impl std::fmt::Debug for DkimKeyList {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DkimKeyList { [REDACTED] }")
    }
}
