/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DkimKeyRotateRequest {
    #[serde(rename = "new_key")]
    pub new_key: Box<models::NewKey>,
}

impl DkimKeyRotateRequest {
    pub fn new(new_key: models::NewKey) -> DkimKeyRotateRequest {
        DkimKeyRotateRequest {
            new_key: Box::new(new_key),
        }
    }
}

impl std::fmt::Debug for DkimKeyRotateRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DkimKeyRotateRequest { [REDACTED] }")
    }
}
