/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DkimSetting : Domain, selector and private key for DKIM signing.
#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DkimSetting {
    /// The Signing Domain Identifier; the d= field in a DKIM-Signature header
    #[serde(rename = "dkim_domain", skip_serializing_if = "Option::is_none")]
    pub dkim_domain: Option<String>,
    /// Encoded in Base64.
    #[serde(rename = "dkim_private_key", skip_serializing_if = "Option::is_none")]
    pub dkim_private_key: Option<String>,
    #[serde(rename = "dkim_selector", skip_serializing_if = "Option::is_none")]
    pub dkim_selector: Option<String>,
}

impl DkimSetting {
    /// Domain, selector and private key for DKIM signing.
    pub fn new() -> DkimSetting {
        DkimSetting {
            dkim_domain: None,
            dkim_private_key: None,
            dkim_selector: None,
        }
    }
}

impl std::fmt::Debug for DkimSetting {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DkimSetting { [REDACTED] }")
    }
}
