/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct DnsSetupRequired {
    /// Human-readable guidance for the DNS records that must be in place before retrying.
    #[serde(rename = "instructions", skip_serializing_if = "Option::is_none")]
    pub instructions: Option<String>,
    /// UUID v4 nonce; also the TXT record value to set. Present only when TXT ownership verification is pending.
    #[serde(rename = "token", skip_serializing_if = "Option::is_none")]
    pub token: Option<String>,
    /// Fully-qualified DNS TXT record name to add. Present only when TXT ownership verification is pending.
    #[serde(rename = "txt_record_name", skip_serializing_if = "Option::is_none")]
    pub txt_record_name: Option<String>,
    /// Value for the DNS TXT record (same as token). Present only when TXT ownership verification is pending.
    #[serde(rename = "txt_record_value", skip_serializing_if = "Option::is_none")]
    pub txt_record_value: Option<String>,
}

impl DnsSetupRequired {
    pub fn new() -> DnsSetupRequired {
        DnsSetupRequired {
            instructions: None,
            token: None,
            txt_record_name: None,
            txt_record_value: None,
        }
    }
}

impl std::fmt::Debug for DnsSetupRequired {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("DnsSetupRequired { [REDACTED] }")
    }
}
