/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Key {
    #[serde(rename = "id")]
    pub id: String,
    /// The public key used to verify webhook signatures
    #[serde(rename = "key")]
    pub key: String,
}

impl Key {
    pub fn new(id: String, key: String) -> Key {
        Key { id, key }
    }
}

impl std::fmt::Debug for Key {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("Key { [REDACTED] }")
    }
}
