/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct LimitInput {
    #[serde(rename = "sends")]
    pub sends: i32,
}

impl LimitInput {
    pub fn new(sends: i32) -> LimitInput {
        LimitInput { sends }
    }
}

impl std::fmt::Debug for LimitInput {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("LimitInput { [REDACTED] }")
    }
}
