/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MailSendBodyTrackingSettings : Settings to adjust open and click tracking for the message. Please note that enabling tracking for your messages requires a subscription that supports open and click tracking.
#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MailSendBodyTrackingSettings {
    #[serde(rename = "click_tracking", skip_serializing_if = "Option::is_none")]
    pub click_tracking: Option<Box<models::MailSendBodyTrackingSettingsClickTracking>>,
    #[serde(rename = "open_tracking", skip_serializing_if = "Option::is_none")]
    pub open_tracking: Option<Box<models::MailSendBodyTrackingSettingsOpenTracking>>,
}

impl MailSendBodyTrackingSettings {
    /// Settings to adjust open and click tracking for the message. Please note that enabling tracking for your messages requires a subscription that supports open and click tracking.
    pub fn new() -> MailSendBodyTrackingSettings {
        MailSendBodyTrackingSettings {
            click_tracking: None,
            open_tracking: None,
        }
    }
}

impl std::fmt::Debug for MailSendBodyTrackingSettings {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("MailSendBodyTrackingSettings { [REDACTED] }")
    }
}
