/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MailSendBody {
    #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<models::Attachment>>,
    /// The campaign identifier. If specified, this ID will be included in all relevant webhooks. It can be up to 48 UTF-8 characters long and must not contain spaces.
    #[serde(rename = "campaign_id", skip_serializing_if = "Option::is_none")]
    pub campaign_id: Option<String>,
    #[serde(rename = "content")]
    pub content: Vec<models::ContentItem>,
    /// If set, you must also provide the matching dkim_selector.
    #[serde(rename = "dkim_domain", skip_serializing_if = "Option::is_none")]
    pub dkim_domain: Option<String>,
    /// Encoded in Base64. If set, you must also provide the matching dkim_domain and dkim_selector.
    #[serde(rename = "dkim_private_key", skip_serializing_if = "Option::is_none")]
    pub dkim_private_key: Option<String>,
    /// If set without a matching dkim_domain, the domain will be taken from the `from` email address.
    #[serde(rename = "dkim_selector", skip_serializing_if = "Option::is_none")]
    pub dkim_selector: Option<String>,
    #[serde(rename = "envelope_from", skip_serializing_if = "Option::is_none")]
    pub envelope_from: Option<Box<models::EmailAddress>>,
    #[serde(rename = "from")]
    pub from: Box<models::EmailAddress>,
    /// A JSON object containing key-value pairs, where both keys (header names) and values must be strings. These pairs represent custom headers to be substituted. Please note the following restrictions and behavior: - Reserved headers: The following headers cannot be modified:   - Authentication-Results   - BCC   - CC   - Content-Transfer-Encoding   - Content-Type   - DKIM-Signature   - From   - Message-ID   - Received   - Reply-To   - Subject   - To - Header precedence: If a header is defined in both the personalizations object and the root headers, the value from personalizations will be used. - Case sensitivity: Headers are treated as case-insensitive. If multiple headers differ only by case, only one will be used, with no guarantee of which one.
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "personalizations")]
    pub personalizations: Vec<models::Personalization>,
    #[serde(rename = "reply_to", skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<Box<models::EmailAddress>>,
    #[serde(rename = "subject")]
    pub subject: String,
    #[serde(rename = "tracking_settings", skip_serializing_if = "Option::is_none")]
    pub tracking_settings: Option<Box<models::MailSendBodyTrackingSettings>>,
    /// Mark these messages as transactional or non-transactional. In order for a message to be marked as non-transactional, it must have exactly one recipient per personalization, and it must be DKIM signed. 400 Bad Request will be returned if there are more than one recipient in any personalization for non-transactional messages. If a message is marked as non-transactional, it changes the sending process as follows:   * List-Unsubscribe and List-Unsubscribe-Post headers will be added, unless you supply your own List-Unsubscribe header, in which case yours is used and neither is added.
    #[serde(
        rename = "transactional",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub transactional: Option<Option<bool>>,
    #[serde(
        rename = "unsubscribe_settings",
        skip_serializing_if = "Option::is_none"
    )]
    pub unsubscribe_settings: Option<Box<models::MailSendBodyUnsubscribeSettings>>,
}

impl MailSendBody {
    pub fn new(
        content: Vec<models::ContentItem>,
        from: models::EmailAddress,
        personalizations: Vec<models::Personalization>,
        subject: String,
    ) -> MailSendBody {
        MailSendBody {
            attachments: None,
            campaign_id: None,
            content,
            dkim_domain: None,
            dkim_private_key: None,
            dkim_selector: None,
            envelope_from: None,
            from: Box::new(from),
            headers: None,
            personalizations,
            reply_to: None,
            subject,
            tracking_settings: None,
            transactional: None,
            unsubscribe_settings: None,
        }
    }
}

impl std::fmt::Debug for MailSendBody {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("MailSendBody { [REDACTED] }")
    }
}
