/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MailSendBodyTrackingSettingsClickTracking {
    /// The name of a configured active click tracking domain. When specified, click tracking links will use this domain instead of the default MailChannels domain. The domain must be registered in your account and have an active status.
    #[serde(rename = "custom_domain_name", skip_serializing_if = "Option::is_none")]
    pub custom_domain_name: Option<String>,
    /// Setting to enable or disable click tracking for the message. This feature allows you to track when a recipient clicks a link in your email.
    #[serde(rename = "enable", skip_serializing_if = "Option::is_none")]
    pub enable: Option<bool>,
}

impl MailSendBodyTrackingSettingsClickTracking {
    pub fn new() -> MailSendBodyTrackingSettingsClickTracking {
        MailSendBodyTrackingSettingsClickTracking {
            custom_domain_name: None,
            enable: None,
        }
    }
}

impl std::fmt::Debug for MailSendBodyTrackingSettingsClickTracking {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("MailSendBodyTrackingSettingsClickTracking { [REDACTED] }")
    }
}
