/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MailSendBodyUnsubscribeSettings : Settings to customize the unsubscribe experience for the message.
#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MailSendBodyUnsubscribeSettings {
    /// The name of a configured active unsubscribe tracking domain. When specified, unsubscribe links will use this domain instead of the default MailChannels domain. The domain must be registered in your account and have an active status.
    #[serde(rename = "custom_domain_name", skip_serializing_if = "Option::is_none")]
    pub custom_domain_name: Option<String>,
}

impl MailSendBodyUnsubscribeSettings {
    /// Settings to customize the unsubscribe experience for the message.
    pub fn new() -> MailSendBodyUnsubscribeSettings {
        MailSendBodyUnsubscribeSettings {
            custom_domain_name: None,
        }
    }
}

impl std::fmt::Debug for MailSendBodyUnsubscribeSettings {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("MailSendBodyUnsubscribeSettings { [REDACTED] }")
    }
}
