/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MetricsRecipientBehaviourBuckets : A series of metrics aggregations bucketed by time interval (e.g. hour, day)
#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MetricsRecipientBehaviourBuckets {
    #[serde(rename = "unsubscribe_delivered")]
    pub unsubscribe_delivered: Vec<models::MetricsBucket>,
    #[serde(rename = "unsubscribed")]
    pub unsubscribed: Vec<models::MetricsBucket>,
}

impl MetricsRecipientBehaviourBuckets {
    /// A series of metrics aggregations bucketed by time interval (e.g. hour, day)
    pub fn new(
        unsubscribe_delivered: Vec<models::MetricsBucket>,
        unsubscribed: Vec<models::MetricsBucket>,
    ) -> MetricsRecipientBehaviourBuckets {
        MetricsRecipientBehaviourBuckets {
            unsubscribe_delivered,
            unsubscribed,
        }
    }
}

impl std::fmt::Debug for MetricsRecipientBehaviourBuckets {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("MetricsRecipientBehaviourBuckets { [REDACTED] }")
    }
}
