/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MetricsVolumeBuckets : A series of metrics aggregations bucketed by time interval (e.g. hour, day)
#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MetricsVolumeBuckets {
    #[serde(rename = "delivered")]
    pub delivered: Vec<models::MetricsBucket>,
    #[serde(rename = "dropped")]
    pub dropped: Vec<models::MetricsBucket>,
    #[serde(rename = "processed")]
    pub processed: Vec<models::MetricsBucket>,
}

impl MetricsVolumeBuckets {
    /// A series of metrics aggregations bucketed by time interval (e.g. hour, day)
    pub fn new(
        delivered: Vec<models::MetricsBucket>,
        dropped: Vec<models::MetricsBucket>,
        processed: Vec<models::MetricsBucket>,
    ) -> MetricsVolumeBuckets {
        MetricsVolumeBuckets {
            delivered,
            dropped,
            processed,
        }
    }
}

impl std::fmt::Debug for MetricsVolumeBuckets {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("MetricsVolumeBuckets { [REDACTED] }")
    }
}
