/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MetricsPerformance {
    /// Count of messages hard-bounced during the specified time range.
    #[serde(rename = "bounced")]
    pub bounced: i32,
    #[serde(rename = "buckets")]
    pub buckets: Box<models::MetricsPerformanceBuckets>,
    /// Count of messages complained during the specified time range.
    #[serde(rename = "complained")]
    pub complained: i32,
    /// Count of messages delivered during the specified time range.
    #[serde(rename = "delivered")]
    pub delivered: i32,
    /// The end of the time range for retrieving message performance metrics (exclusive).
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Count of messages processed during the specified time range.
    #[serde(rename = "processed")]
    pub processed: i32,
    /// The beginning of the time range for retrieving message performance metrics (inclusive).
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl MetricsPerformance {
    pub fn new(
        bounced: i32,
        buckets: models::MetricsPerformanceBuckets,
        complained: i32,
        delivered: i32,
        processed: i32,
    ) -> MetricsPerformance {
        MetricsPerformance {
            bounced,
            buckets: Box::new(buckets),
            complained,
            delivered,
            end_time: None,
            processed,
            start_time: None,
        }
    }
}

impl std::fmt::Debug for MetricsPerformance {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("MetricsPerformance { [REDACTED] }")
    }
}
