/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MetricsRecipientBehaviour {
    #[serde(rename = "buckets")]
    pub buckets: Box<models::MetricsRecipientBehaviourBuckets>,
    /// The end of the time range for retrieving recipient behaviour metrics (exclusive).
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The beginning of the time range for retrieving recipient behaviour metrics (inclusive).
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Count of recipients of delivered messages that include at least one of the unsubscribe link or unsubscribe headers. Since the unsubscribe feature requires exactly one recipient per message, this count also represents the total number of delivered messages.
    #[serde(rename = "unsubscribe_delivered")]
    pub unsubscribe_delivered: i32,
    /// Count of unsubscribed events by recipients.
    #[serde(rename = "unsubscribed")]
    pub unsubscribed: i32,
}

impl MetricsRecipientBehaviour {
    pub fn new(
        buckets: models::MetricsRecipientBehaviourBuckets,
        unsubscribe_delivered: i32,
        unsubscribed: i32,
    ) -> MetricsRecipientBehaviour {
        MetricsRecipientBehaviour {
            buckets: Box::new(buckets),
            end_time: None,
            start_time: None,
            unsubscribe_delivered,
            unsubscribed,
        }
    }
}

impl std::fmt::Debug for MetricsRecipientBehaviour {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("MetricsRecipientBehaviour { [REDACTED] }")
    }
}
