/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MetricsSender {
    #[serde(rename = "bounced")]
    pub bounced: i32,
    #[serde(rename = "delivered")]
    pub delivered: i32,
    #[serde(rename = "dropped")]
    pub dropped: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "processed")]
    pub processed: i32,
}

impl MetricsSender {
    pub fn new(
        bounced: i32,
        delivered: i32,
        dropped: i32,
        name: String,
        processed: i32,
    ) -> MetricsSender {
        MetricsSender {
            bounced,
            delivered,
            dropped,
            name,
            processed,
        }
    }
}

impl std::fmt::Debug for MetricsSender {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("MetricsSender { [REDACTED] }")
    }
}
