/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MetricsSenderResponse {
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<chrono::DateTime<chrono::FixedOffset>>,
    #[serde(rename = "limit")]
    pub limit: i32,
    #[serde(rename = "offset")]
    pub offset: i32,
    #[serde(rename = "senders")]
    pub senders: Vec<models::MetricsSender>,
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// The total number of senders in this category that sent messages in the given time range.
    #[serde(rename = "total")]
    pub total: i32,
}

impl MetricsSenderResponse {
    pub fn new(
        limit: i32,
        offset: i32,
        senders: Vec<models::MetricsSender>,
        total: i32,
    ) -> MetricsSenderResponse {
        MetricsSenderResponse {
            end_time: None,
            limit,
            offset,
            senders,
            start_time: None,
            total,
        }
    }
}

impl std::fmt::Debug for MetricsSenderResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("MetricsSenderResponse { [REDACTED] }")
    }
}
