/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MetricsPerformanceBuckets : A series of metrics aggregations bucketed by time interval (e.g. hour, day)
#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MetricsPerformanceBuckets {
    #[serde(rename = "bounced")]
    pub bounced: Vec<models::MetricsBucket>,
    #[serde(rename = "complained")]
    pub complained: Vec<models::MetricsBucket>,
    #[serde(rename = "delivered")]
    pub delivered: Vec<models::MetricsBucket>,
    #[serde(rename = "processed")]
    pub processed: Vec<models::MetricsBucket>,
}

impl MetricsPerformanceBuckets {
    /// A series of metrics aggregations bucketed by time interval (e.g. hour, day)
    pub fn new(
        bounced: Vec<models::MetricsBucket>,
        complained: Vec<models::MetricsBucket>,
        delivered: Vec<models::MetricsBucket>,
        processed: Vec<models::MetricsBucket>,
    ) -> MetricsPerformanceBuckets {
        MetricsPerformanceBuckets {
            bounced,
            complained,
            delivered,
            processed,
        }
    }
}

impl std::fmt::Debug for MetricsPerformanceBuckets {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("MetricsPerformanceBuckets { [REDACTED] }")
    }
}
