/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MetricsBucket : Represents a time-based bucket for aggregating metrics data. Each bucket corresponds to a specific time interval, with the `period_start` indicating the beginning of that interval. The `count` field represents the number of events or occurrences that fall within that time period.
#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MetricsBucket {
    /// The number of events or occurrences aggregated within this time period.
    #[serde(rename = "count")]
    pub count: i32,
    /// The starting date and time of the time period this bucket represents.
    #[serde(rename = "period_start")]
    pub period_start: chrono::DateTime<chrono::FixedOffset>,
}

impl MetricsBucket {
    /// Represents a time-based bucket for aggregating metrics data. Each bucket corresponds to a specific time interval, with the `period_start` indicating the beginning of that interval. The `count` field represents the number of events or occurrences that fall within that time period.
    pub fn new(count: i32, period_start: chrono::DateTime<chrono::FixedOffset>) -> MetricsBucket {
        MetricsBucket {
            count,
            period_start,
        }
    }
}

impl std::fmt::Debug for MetricsBucket {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("MetricsBucket { [REDACTED] }")
    }
}
