/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MetricsVolume {
    #[serde(rename = "buckets")]
    pub buckets: Box<models::MetricsVolumeBuckets>,
    /// Count of messages delivered during the specified time range.
    #[serde(rename = "delivered")]
    pub delivered: i32,
    /// Count of messages dropped during the specified time range.
    #[serde(rename = "dropped")]
    pub dropped: i32,
    /// The end of the time range for retrieving message volume metrics (exclusive).
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Count of messages processed during the specified time range.
    #[serde(rename = "processed")]
    pub processed: i32,
    /// The beginning of the time range for retrieving message volume metrics (inclusive).
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<chrono::DateTime<chrono::FixedOffset>>,
}

impl MetricsVolume {
    pub fn new(
        buckets: models::MetricsVolumeBuckets,
        delivered: i32,
        dropped: i32,
        processed: i32,
    ) -> MetricsVolume {
        MetricsVolume {
            buckets: Box::new(buckets),
            delivered,
            dropped,
            end_time: None,
            processed,
            start_time: None,
        }
    }
}

impl std::fmt::Debug for MetricsVolume {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("MetricsVolume { [REDACTED] }")
    }
}
