/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MetricsEngagementBuckets : A series of metrics aggregations bucketed by time interval (e.g. hour, day)
#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MetricsEngagementBuckets {
    #[serde(rename = "click")]
    pub click: Vec<models::MetricsBucket>,
    #[serde(rename = "click_tracking_delivered")]
    pub click_tracking_delivered: Vec<models::MetricsBucket>,
    #[serde(rename = "open")]
    pub open: Vec<models::MetricsBucket>,
    #[serde(rename = "open_tracking_delivered")]
    pub open_tracking_delivered: Vec<models::MetricsBucket>,
    #[serde(rename = "unique_click", skip_serializing_if = "Option::is_none")]
    pub unique_click: Option<Vec<models::MetricsBucket>>,
    #[serde(
        rename = "unique_click_tracking_delivered",
        skip_serializing_if = "Option::is_none"
    )]
    pub unique_click_tracking_delivered: Option<Vec<models::MetricsBucket>>,
    #[serde(rename = "unique_open", skip_serializing_if = "Option::is_none")]
    pub unique_open: Option<Vec<models::MetricsBucket>>,
    #[serde(
        rename = "unique_open_tracking_delivered",
        skip_serializing_if = "Option::is_none"
    )]
    pub unique_open_tracking_delivered: Option<Vec<models::MetricsBucket>>,
}

impl MetricsEngagementBuckets {
    /// A series of metrics aggregations bucketed by time interval (e.g. hour, day)
    pub fn new(
        click: Vec<models::MetricsBucket>,
        click_tracking_delivered: Vec<models::MetricsBucket>,
        open: Vec<models::MetricsBucket>,
        open_tracking_delivered: Vec<models::MetricsBucket>,
    ) -> MetricsEngagementBuckets {
        MetricsEngagementBuckets {
            click,
            click_tracking_delivered,
            open,
            open_tracking_delivered,
            unique_click: None,
            unique_click_tracking_delivered: None,
            unique_open: None,
            unique_open_tracking_delivered: None,
        }
    }
}

impl std::fmt::Debug for MetricsEngagementBuckets {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("MetricsEngagementBuckets { [REDACTED] }")
    }
}
