/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct MetricsEngagement {
    #[serde(rename = "buckets")]
    pub buckets: Box<models::MetricsEngagementBuckets>,
    /// Count of click events by recipients.
    #[serde(rename = "click")]
    pub click: i32,
    /// Count of recipients of delivered messages with HTML content that contains tracked click URLs, where click tracking is enabled in the send request.
    #[serde(rename = "click_tracking_delivered")]
    pub click_tracking_delivered: i32,
    /// The end of the time range for retrieving message engagement metrics (exclusive).
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Count of open events by recipients.
    #[serde(rename = "open")]
    pub open: i32,
    /// Count of recipients of delivered messages with HTML content where open tracking was enabled in the send request.
    #[serde(rename = "open_tracking_delivered")]
    pub open_tracking_delivered: i32,
    /// The beginning of the time range for retrieving message engagement metrics (inclusive).
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<chrono::DateTime<chrono::FixedOffset>>,
    /// Count of distinct messages that had at least one click event. Unlike `click`, each message is counted at most once regardless of how many links were clicked or how many times. Use this to compute click rates without exceeding 100%.
    #[serde(rename = "unique_click", skip_serializing_if = "Option::is_none")]
    pub unique_click: Option<i32>,
    /// Count of distinct messages delivered with click tracking enabled (message-level, not recipient-level). Use as the denominator when computing unique click rates.
    #[serde(
        rename = "unique_click_tracking_delivered",
        skip_serializing_if = "Option::is_none"
    )]
    pub unique_click_tracking_delivered: Option<i32>,
    /// Count of distinct messages that had at least one open event. Unlike `open`, each message is counted at most once regardless of how many times its tracking pixel was fired. Use this to compute open rates without exceeding 100%.
    #[serde(rename = "unique_open", skip_serializing_if = "Option::is_none")]
    pub unique_open: Option<i32>,
    /// Count of distinct messages delivered with open tracking enabled (message-level, not recipient-level). Use as the denominator when computing unique open rates.
    #[serde(
        rename = "unique_open_tracking_delivered",
        skip_serializing_if = "Option::is_none"
    )]
    pub unique_open_tracking_delivered: Option<i32>,
}

impl MetricsEngagement {
    pub fn new(
        buckets: models::MetricsEngagementBuckets,
        click: i32,
        click_tracking_delivered: i32,
        open: i32,
        open_tracking_delivered: i32,
    ) -> MetricsEngagement {
        MetricsEngagement {
            buckets: Box::new(buckets),
            click,
            click_tracking_delivered,
            end_time: None,
            open,
            open_tracking_delivered,
            start_time: None,
            unique_click: None,
            unique_click_tracking_delivered: None,
            unique_open: None,
            unique_open_tracking_delivered: None,
        }
    }
}

impl std::fmt::Debug for MetricsEngagement {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("MetricsEngagement { [REDACTED] }")
    }
}
