/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct Personalization {
    #[serde(rename = "bcc", skip_serializing_if = "Option::is_none")]
    pub bcc: Option<Vec<models::EmailAddress>>,
    #[serde(rename = "cc", skip_serializing_if = "Option::is_none")]
    pub cc: Option<Vec<models::EmailAddress>>,
    /// If set, you must also provide the matching dkim_selector.
    #[serde(rename = "dkim_domain", skip_serializing_if = "Option::is_none")]
    pub dkim_domain: Option<String>,
    /// Encoded in Base64. If set, you must also provide the matching dkim_domain and dkim_selector.
    #[serde(rename = "dkim_private_key", skip_serializing_if = "Option::is_none")]
    pub dkim_private_key: Option<String>,
    /// If set without a matching dkim_domain, the domain will be taken from the `from` email address.
    #[serde(rename = "dkim_selector", skip_serializing_if = "Option::is_none")]
    pub dkim_selector: Option<String>,
    /// A JSON object containing key-value pairs of variables to set for template rendering. Keys must be strings, and values can be one of the following types: * string * boolean * number * list, whose values are all of permitted types * map, whose keys must be strings, and whose values are all of permitted types
    #[serde(
        rename = "dynamic_template_data",
        skip_serializing_if = "Option::is_none"
    )]
    pub dynamic_template_data: Option<serde_json::Value>,
    #[serde(rename = "envelope_from", skip_serializing_if = "Option::is_none")]
    pub envelope_from: Option<Box<models::EmailAddress>>,
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<Box<models::EmailAddress>>,
    /// A JSON object containing key-value pairs, where both keys (header names) and values must be strings. These pairs represent custom headers to be substituted. Please note the following restrictions and behavior: - Reserved headers: The following headers cannot be modified:   - Authentication-Results   - BCC   - CC   - Content-Transfer-Encoding   - Content-Type   - DKIM-Signature   - From   - Message-ID   - Received   - Reply-To   - Subject   - To - Header precedence: If a header is defined in both the personalizations object and the root headers, the value from personalizations will be used. - Case sensitivity: Headers are treated as case-insensitive. If multiple headers differ only by case, only one will be used, with no guarantee of which one.
    #[serde(rename = "headers", skip_serializing_if = "Option::is_none")]
    pub headers: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "reply_to", skip_serializing_if = "Option::is_none")]
    pub reply_to: Option<Box<models::EmailAddress>>,
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    #[serde(rename = "to")]
    pub to: Vec<models::EmailAddress>,
}

impl Personalization {
    pub fn new(to: Vec<models::EmailAddress>) -> Personalization {
        Personalization {
            bcc: None,
            cc: None,
            dkim_domain: None,
            dkim_private_key: None,
            dkim_selector: None,
            dynamic_template_data: None,
            envelope_from: None,
            from: None,
            headers: None,
            reply_to: None,
            subject: None,
            to,
        }
    }
}

impl std::fmt::Debug for Personalization {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("Personalization { [REDACTED] }")
    }
}
