/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct PostCustomTrackingDomainRequest {
    /// The hostname to register as a custom tracking domain (e.g., click.example.com). The hostname must have a CNAME record pointing to `links.mailchannels.net`.
    #[serde(rename = "hostname")]
    pub hostname: String,
    /// A unique label used to select this domain at message send time
    #[serde(rename = "name")]
    pub name: String,
    /// The event type this domain handles
    #[serde(rename = "scope")]
    pub scope: Scope,
}

impl PostCustomTrackingDomainRequest {
    pub fn new(hostname: String, name: String, scope: Scope) -> PostCustomTrackingDomainRequest {
        PostCustomTrackingDomainRequest {
            hostname,
            name,
            scope,
        }
    }
}
/// The event type this domain handles
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Scope {
    #[serde(rename = "click")]
    Click,
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "unsubscribe")]
    Unsubscribe,
}

impl Default for Scope {
    fn default() -> Scope {
        Self::Click
    }
}

impl std::fmt::Debug for PostCustomTrackingDomainRequest {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("PostCustomTrackingDomainRequest { [REDACTED] }")
    }
}
