/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SmtpPassword {
    /// Whether the SMTP password is enabled
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// The SMTP password ID for the sub-account
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// SMTP password for the sub-account
    #[serde(rename = "smtp_password", skip_serializing_if = "Option::is_none")]
    pub smtp_password: Option<String>,
}

impl SmtpPassword {
    pub fn new() -> SmtpPassword {
        SmtpPassword {
            enabled: None,
            id: None,
            smtp_password: None,
        }
    }
}

impl std::fmt::Debug for SmtpPassword {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SmtpPassword { [REDACTED] }")
    }
}
