/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SubAccountDetails {
    #[serde(rename = "company_name", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<String>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "handle")]
    pub handle: String,
}

impl SubAccountDetails {
    pub fn new(enabled: bool, handle: String) -> SubAccountDetails {
        SubAccountDetails {
            company_name: None,
            enabled,
            handle,
        }
    }
}

impl std::fmt::Debug for SubAccountDetails {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SubAccountDetails { [REDACTED] }")
    }
}
