/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SuppressionEntry {
    #[serde(
        rename = "notes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub notes: Option<Option<String>>,
    #[serde(rename = "recipient")]
    pub recipient: String,
    #[serde(rename = "suppression_types", skip_serializing_if = "Option::is_none")]
    pub suppression_types: Option<Vec<SuppressionTypes>>,
}

impl SuppressionEntry {
    pub fn new(recipient: String) -> SuppressionEntry {
        SuppressionEntry {
            notes: None,
            recipient,
            suppression_types: None,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SuppressionTypes {
    #[serde(rename = "transactional")]
    Transactional,
    #[serde(rename = "non-transactional")]
    NonTransactional,
}

impl Default for SuppressionTypes {
    fn default() -> SuppressionTypes {
        Self::Transactional
    }
}

impl std::fmt::Debug for SuppressionEntry {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SuppressionEntry { [REDACTED] }")
    }
}
