/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SuppressionListResponse {
    #[serde(rename = "suppression_list")]
    pub suppression_list: Vec<models::SuppressionEntryResponse>,
}

impl SuppressionListResponse {
    pub fn new(suppression_list: Vec<models::SuppressionEntryResponse>) -> SuppressionListResponse {
        SuppressionListResponse { suppression_list }
    }
}

impl std::fmt::Debug for SuppressionListResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SuppressionListResponse { [REDACTED] }")
    }
}
