/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SuppressionListInput {
    /// If true, the parent account creates suppression entries for all associated sub-accounts. This field is only applicable to parent accounts. Sub-accounts cannot create entries for other sub-accounts.
    #[serde(
        rename = "add_to_sub_accounts",
        skip_serializing_if = "Option::is_none"
    )]
    pub add_to_sub_accounts: Option<bool>,
    /// The total number of suppression entries to create, for the parent and/or its sub-accounts, must not exceed 1000.
    #[serde(rename = "suppression_entries")]
    pub suppression_entries: Vec<models::SuppressionEntry>,
}

impl SuppressionListInput {
    pub fn new(suppression_entries: Vec<models::SuppressionEntry>) -> SuppressionListInput {
        SuppressionListInput {
            add_to_sub_accounts: None,
            suppression_entries,
        }
    }
}

impl std::fmt::Debug for SuppressionListInput {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SuppressionListInput { [REDACTED] }")
    }
}
