/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct UsageStats {
    /// The effective monthly limit for the current billing period. A limit of zero means the account cannot send any messages. For sub-accounts with no explicit limit set (i.e., -1), the monthly limit for the parent account is returned.
    #[serde(rename = "monthly_limit")]
    pub monthly_limit: i32,
    /// The end date of the current billing period (ISO 8601 format).
    #[serde(rename = "period_end_date", skip_serializing_if = "Option::is_none")]
    pub period_end_date: Option<chrono::NaiveDate>,
    /// The start date of the current billing period (ISO 8601 format).
    #[serde(rename = "period_start_date", skip_serializing_if = "Option::is_none")]
    pub period_start_date: Option<chrono::NaiveDate>,
    /// The total usage for the current billing period.
    #[serde(rename = "total_usage")]
    pub total_usage: i64,
}

impl UsageStats {
    pub fn new(monthly_limit: i32, total_usage: i64) -> UsageStats {
        UsageStats {
            monthly_limit,
            period_end_date: None,
            period_start_date: None,
            total_usage,
        }
    }
}

impl std::fmt::Debug for UsageStats {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("UsageStats { [REDACTED] }")
    }
}
