/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookResponse : The HTTP response returned by the webhook, including status code and response body. A null value indicates no response was received. Possible reasons include timeouts, connection failures, or other network-related issues.
#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WebhookResponse {
    /// Response body from webhook. Returns an error if unprocessable or too large.
    #[serde(rename = "body", skip_serializing_if = "Option::is_none")]
    pub body: Option<String>,
    /// HTTP status code returned by the webhook
    #[serde(rename = "status")]
    pub status: i32,
}

impl WebhookResponse {
    /// The HTTP response returned by the webhook, including status code and response body. A null value indicates no response was received. Possible reasons include timeouts, connection failures, or other network-related issues.
    pub fn new(status: i32) -> WebhookResponse {
        WebhookResponse { body: None, status }
    }
}

impl std::fmt::Debug for WebhookResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("WebhookResponse { [REDACTED] }")
    }
}
