/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookBatchDuration : Duration of the webhook batch. measured from the time the request was sent to the webhook endpoint until the response was received.
#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WebhookBatchDuration {
    #[serde(rename = "unit")]
    pub unit: Unit,
    #[serde(rename = "value")]
    pub value: i32,
}

impl WebhookBatchDuration {
    /// Duration of the webhook batch. measured from the time the request was sent to the webhook endpoint until the response was received.
    pub fn new(unit: Unit, value: i32) -> WebhookBatchDuration {
        WebhookBatchDuration { unit, value }
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Unit {
    #[serde(rename = "milliseconds")]
    Milliseconds,
}

impl Default for Unit {
    fn default() -> Unit {
        Self::Milliseconds
    }
}

impl std::fmt::Debug for WebhookBatchDuration {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("WebhookBatchDuration { [REDACTED] }")
    }
}
