/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WebhookResendResponse {
    /// Unique identifier for the webhook batch
    #[serde(rename = "batch_id")]
    pub batch_id: i64,
    /// Timestamp of when the webhook batch was created
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// Customer handle associated with the webhook batch
    #[serde(rename = "customer_handle")]
    pub customer_handle: String,
    /// Duration of the webhook batch in milliseconds, measured from the time the request was sent to the webhook endpoint until the response was received. Null indicates that no response was returned from the webhook endpoint.
    #[serde(
        rename = "duration_in_ms",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub duration_in_ms: Option<Option<i32>>,
    /// Number of events in the webhook batch
    #[serde(rename = "event_count")]
    pub event_count: i32,
    /// HTTP status code returned by the webhook endpoint. Valid values are 100-599. Null indicates that no response was returned from the webhook endpoint.
    #[serde(
        rename = "status_code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status_code: Option<Option<i32>>,
    /// Webhook URL to which events in the batch were posted
    #[serde(rename = "webhook")]
    pub webhook: String,
}

impl WebhookResendResponse {
    pub fn new(
        batch_id: i64,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        customer_handle: String,
        event_count: i32,
        webhook: String,
    ) -> WebhookResendResponse {
        WebhookResendResponse {
            batch_id,
            created_at,
            customer_handle,
            duration_in_ms: None,
            event_count,
            status_code: None,
            webhook,
        }
    }
}

impl std::fmt::Debug for WebhookResendResponse {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("WebhookResendResponse { [REDACTED] }")
    }
}
