/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WebhookBatch {
    /// Unique identifier for the webhook batch
    #[serde(rename = "batch_id")]
    pub batch_id: i64,
    /// Timestamp of when the webhook batch was created
    #[serde(rename = "created_at")]
    pub created_at: chrono::DateTime<chrono::FixedOffset>,
    /// Customer handle associated with the webhook batch
    #[serde(rename = "customer_handle")]
    pub customer_handle: String,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<Box<models::WebhookBatchDuration>>,
    /// Number of events in the webhook batch
    #[serde(rename = "event_count")]
    pub event_count: i32,
    /// Status of the webhook batch. no_response: no response returned from the webhook endpoint.
    #[serde(rename = "status")]
    pub status: Status,
    /// HTTP status code returned by the webhook endpoint
    #[serde(
        rename = "status_code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub status_code: Option<Option<i32>>,
    /// Webhook endpoint to which events in the batch were posted
    #[serde(rename = "webhook")]
    pub webhook: String,
}

impl WebhookBatch {
    pub fn new(
        batch_id: i64,
        created_at: chrono::DateTime<chrono::FixedOffset>,
        customer_handle: String,
        event_count: i32,
        status: Status,
        webhook: String,
    ) -> WebhookBatch {
        WebhookBatch {
            batch_id,
            created_at,
            customer_handle,
            duration: None,
            event_count,
            status,
            status_code: None,
            webhook,
        }
    }
}
/// Status of the webhook batch. no_response: no response returned from the webhook endpoint.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "1xx_response")]
    Variant1xxResponse,
    #[serde(rename = "2xx_response")]
    Variant2xxResponse,
    #[serde(rename = "3xx_response")]
    Variant3xxResponse,
    #[serde(rename = "4xx_response")]
    Variant4xxResponse,
    #[serde(rename = "5xx_response")]
    Variant5xxResponse,
    #[serde(rename = "no_response")]
    NoResponse,
}

impl Default for Status {
    fn default() -> Status {
        Self::Variant1xxResponse
    }
}

impl std::fmt::Debug for WebhookBatch {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("WebhookBatch { [REDACTED] }")
    }
}
