/*
 * Email API
 *
 * This is the API reference for Email API. Here, you'll find more detailed information on every endpoint, including parameters, response formats, and error codes.
 *
 * The version of the OpenAPI document: 1.7.1
 * Contact: support@mailchannels.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct WebhookValidationRequestBody {
    /// Optional identifier in the webhook payload. If not provided, a value will be automatically generated.
    #[serde(rename = "request_id", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
}

impl WebhookValidationRequestBody {
    pub fn new() -> WebhookValidationRequestBody {
        WebhookValidationRequestBody { request_id: None }
    }
}

impl std::fmt::Debug for WebhookValidationRequestBody {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("WebhookValidationRequestBody { [REDACTED] }")
    }
}
